% test_stokes_neumann_bvp.m
% Single-p Neumann BVP test with slice-target visualization.

clear;

root_dir = pwd;
if ~isfolder(fullfile(root_dir, 'matlab'))
  root_dir = fileparts(root_dir);
end
addpath(fullfile(root_dir, 'matlab'));
addpath(fullfile(root_dir, 'src'));
addpath(fullfile(root_dir, 'test'));
addpath(fullfile(root_dir, 'test', 'helpers'));

p = 24;
Shape = 'Y43';
factor = 1.5;

nu = p + 1;
nv = 2 * p;
np = nu * nv;
r = zeros(3, np);
nx = zeros(3, np);
xu = zeros(3, np);
xv = zeros(3, np);
w = zeros(np, 1);
[r, nx, xu, xv, w] = build_geometry_bvp_mex(p, np, Shape, r, nx, xu, xv, w);
fprintf('Building matrices for shape=%s, p=%d (size %d x %d)\n', Shape, p, 3*np, 3*np);

TMat = zeros(3*np, 3*np);
TMat = kerneldSMatrix_mex(p, np, 3*np, r, nx, w(:), TMat);

% Neumann BVP generated by an interior point source
s = struct('x', r, 'nx', nx);
[~, gwt] = gauss(p+1); gwt = gwt';
wt = pi/p * repmat(gwt', 2*p, 1) ./ sin(gl_grid(p));
s.w = (w(:) .* wt(:))';

y_force.x = [0.1; 0.2; -0.3] / 4;
y_force.w = 1;
pt_force = [1; 1/2; 1/3];

Anhom = zeros(3*size(s.x, 2), 3*size(y_force.x, 2));
Anhom = Sto3dSLPnmat_mex(size(s.x, 2), size(y_force.x, 2), ...
  3*size(s.x, 2), 3*size(y_force.x, 2), ...
  s.x, s.nx, y_force.x, y_force.w(:), 0, Anhom);
rhsn = Anhom * pt_force;
rhsn = reshape(rhsn, [], 3)';

% dSL_Stk_3D branch: traction jump on interior limit
TMat = -eye(size(TMat)) / 2 + TMat;

%% Baseline GMRES solve
b = rhsn(:);
gmres_tol = 1e-6;
maxit = min(1000, numel(b));
L = speye(3*np);
[mu_gmres, flag_gmres, relres_gmres, iter_gmres, resvec_gmres] = gmres(TMat, b, [], gmres_tol, maxit, @(v) L*v);
fprintf('GMRES: flag=%d, iterations=%d, residual=%.6e\n', flag_gmres, numel(resvec_gmres)-1, relres_gmres);
% evaluate velocity
[s, t, vis] = prepare_bvp_slice(p, r, w, mu_gmres, factor);
u_num = reshape(Sto3dSLPmat_mex(t.n, s.n, 3*t.n, 3*s.n, t.x, s.x, s.w, 0, zeros(3*t.n, 3*s.n)) * s.mu, [], 3)';
u_ref = reshape(Sto3dSLPmat_mex(t.n, 1, 3*t.n, 3, t.x, y_force.x, y_force.w(:), 0, zeros(3*t.n, 3)) * pt_force, [], 3)';
errS = vecnorm(u_num - u_ref) / max(vecnorm(u_ref));
fprintf('GMRES velocity error: max=%.6e, mean=%.6e\n', max(errS), mean(errS));
figure(1); clf; plot_bvp_slice(vis, u_num, errS);

%% Robust solve via truncated SVD
svd_tol = 1e-12;
[U_svd, S_svd, V_svd] = svd(TMat);
diagS = diag(S_svd);
idx = diagS > svd_tol;
mu_svd = V_svd(:,idx) * ((U_svd(:,idx)' * b) ./ diagS(idx));
fprintf('SVD: retained rank=%d, residual=%.6e\n', nnz(idx), norm(TMat*mu_svd-b)/norm(b));
% evaluate velocity
[s, t, vis] = prepare_bvp_slice(p, r, w, mu_svd, factor);
u_num = reshape(Sto3dSLPmat_mex(t.n, s.n, 3*t.n, 3*s.n, t.x, s.x, s.w, 0, zeros(3*t.n, 3*s.n)) * s.mu, [], 3)';
u_ref = reshape(Sto3dSLPmat_mex(t.n, 1, 3*t.n, 3, t.x, y_force.x, y_force.w(:), 0, zeros(3*t.n, 3)) * pt_force, [], 3)';
errS = vecnorm(u_num - u_ref) / max(vecnorm(u_ref));
fprintf('SVD velocity error: max=%.6e, mean=%.6e\n', max(errS), mean(errS));
figure(2); clf; plot_bvp_slice(vis, u_num, errS);
% on-surface Neumann residual
errN = vecnorm(reshape(TMat*mu_svd-b, 3, []));
fprintf('On-surface traction residual: max=%.3e, mean=%.3e\n', max(errN), mean(errN));

keyboard
