% test_stokes_neumann_bvp.m
% Single-p Neumann BVP test with slice-target visualization.

clear; clc;

root_dir = pwd;
if ~isfolder(fullfile(root_dir, 'matlab'))
  root_dir = fileparts(root_dir);
end

addpath(fullfile(root_dir, 'matlab'));
addpath(fullfile(root_dir, 'src'));
addpath(fullfile(root_dir, 'test'));

p = 24;
Shape = 'Y43';
factor = 1.5;

nu = p + 1;
nv = 2 * p;
np = nu * nv;
r = zeros(3, np);
nx = zeros(3, np);
xu = zeros(3, np);
xv = zeros(3, np);
w = zeros(np, 1);
[r, nx, xu, xv, w] = build_geometry_bvp_mex(p, np, Shape, r, nx, xu, xv, w);
fprintf('Building matrices for shape=%s, p=%d (size %d x %d)\n', Shape, p, 3*np, 3*np);

TMat = zeros(3*np, 3*np);
TMat = kerneldSMatrix_mex(p, np, 3*np, r, nx, w(:), TMat);

% Neumann BVP generated by an interior point source
s = struct('x', r, 'nx', nx);
[~, gwt] = gauss(p+1); gwt = gwt';
wt = pi/p * repmat(gwt', 2*p, 1) ./ sin(gl_grid(p));
s.w = (w(:) .* wt(:))';

y_force.x = [0.1; 0.2; -0.3] / 4;
y_force.w = 1;
pt_force = [1; 1/2; 1/3];

Anhom = zeros(3*size(s.x, 2), 3*size(y_force.x, 2));
Anhom = Sto3dSLPnmat_mex(size(s.x, 2), size(y_force.x, 2), ...
  3*size(s.x, 2), 3*size(y_force.x, 2), ...
  s.x, s.nx, y_force.x, y_force.w(:), 0, Anhom);
rhsn = Anhom * pt_force;
rhsn = reshape(rhsn, [], 3)';

% dSL_Stk_3D branch: traction jump on interior limit
TMat = -eye(size(TMat)) / 2 + TMat;

% Robust solve via truncated SVD
[U_svd, S_svd, V_svd] = svd(TMat);
diagS = diag(S_svd);
idx = abs(diagS) > 1e-12;
invAs = V_svd(:, idx) * inv(S_svd(idx, idx)) * U_svd(:, idx)';
muS = reshape(invAs * rhsn(:), 3, [])';

% Build a closed surface (caps + seam) for inpolyhedron masking
Xin = s.x';
Xin = Xin(:);
[mu, mv, m] = spharm_grid_size([], size(Xin, 1) / 3);
nv = size(Xin, 2);
Xin = reshape(Xin, [], 3 * nv);

XCap = zeros((m + 3) * (2 * m), 3);
[u, v] = gl_grid(m);
u = reshape(u, mu, mv);
v = reshape(v, mu, mv);
u = [pi * ones(1, mv); u; zeros(1, mv)];
v = [v; v(1:2, :)];

for jj = 1:3
    XCap(:, jj) = sumBasis(shAna(Xin(:, jj)), 'Ynm', true, u(:), v(:));
end

xsurf = reshape(XCap(:, 1), m + 3, 2 * m);
ysurf = reshape(XCap(:, 2), m + 3, 2 * m);
zsurf = reshape(XCap(:, 3), m + 3, 2 * m);

xsurf = [xsurf, xsurf(:, 1)];
ysurf = [ysurf, ysurf(:, 1)];
zsurf = [zsurf, zsurf(:, 1)];

% Slice targets on y=0 plane, masked outside inflated surface
xlimval = [-2, 2];
zlimval = [-2, 2];
nxg = 200;
nzg = 200;
gx = linspace(xlimval(1), xlimval(2), nxg + 1);
gz = linspace(zlimval(1), zlimval(2), nzg + 1);
[XX, ZZ] = meshgrid(gx, gz);

tx = [XX(:), zeros(numel(XX), 1), ZZ(:)]';
FV = surf2patch(factor * xsurf, factor * ysurf, factor * zsurf, 'triangles');
IN = inpolyhedron(FV, tx');
OUT = ~IN;

t = struct();
t.x = [XX(OUT), zeros(nnz(OUT), 1), ZZ(OUT)]';

% Evaluate numerical and reference fields on slice targets
fhomA = zeros(3*size(t.x, 2), 3*size(y_force.x, 2));
fhomA = Sto3dSLPmat_mex(size(t.x, 2), size(y_force.x, 2), ...
  3*size(t.x, 2), 3*size(y_force.x, 2), ...
  t.x, y_force.x, y_force.w(:), 0, fhomA);
fhom = fhomA * pt_force;
fhom = reshape(fhom, [], 3)';
fnumA = zeros(3*size(t.x, 2), 3*size(s.x, 2));
fnumA = Sto3dSLPmat_mex(size(t.x, 2), size(s.x, 2), ...
  3*size(t.x, 2), 3*size(s.x, 2), ...
  t.x, s.x, s.w(:), 0, fnumA);
fnum = fnumA * reshape(muS, [], 1);
fnum = reshape(fnum, [], 3)';

errS = sqrt(sum((fnum - fhom).^2, 1)) / max(sqrt(sum(fhom.^2, 1)));

% Visualize velocity magnitude and error on the same slice
uSlice = nan(size(XX));
uMag = sqrt(fnum(1, :).^2 + fnum(3, :).^2);
uSlice(OUT) = uMag;

figure(2); clf;
subplot(1,2,1);
plt = surf(xsurf, zsurf, ysurf);
plt.EdgeAlpha = 0.0;
plt.FaceColor = 0.9 * [1 1 1];
plt.FaceAlpha = 0.8;
axis equal; hold on; view(0, 90);

pc = pcolor(gx, gz, uSlice);
set(pc, 'FaceColor', 'interp', 'LineStyle', 'none');
colormap(parula);
colorbar;
title('|u| on y=0 slice');

subplot(1,2,2);
plt2 = surf(xsurf, zsurf, ysurf);
plt2.EdgeAlpha = 0.0;
plt2.FaceColor = 0.9 * [1 1 1];
plt2.FaceAlpha = 0.8;
axis equal; hold on; view(0, 90);

scatter3(t.x(1, :), t.x(3, :), t.x(2, :), 10, log10(errS), 'filled');
colorbar;
title('log10 relative error on slice');

fprintf('Slice error stats: max=%.3e, mean=%.3e\n', max(errS), mean(errS));

% Optional: on-surface Neumann residual of traction equation
fpnum = TMat * reshape(muS.', [], 1);
fpnum = reshape(fpnum, 3, []);
errN = sqrt(sum((fpnum - rhsn).^2, 1));
fprintf('On-surface traction residual: max=%.3e, mean=%.3e\n', max(errN), mean(errN));

keyboard
