% test_stokes_dirichlet_bvp.m
% Single-p Dirichlet BVP test with slice-target visualization.

clear; clc;

root_dir = pwd;
if ~isfolder(fullfile(root_dir, 'matlab'))
  root_dir = fileparts(root_dir);
end
addpath(fullfile(root_dir, 'matlab'));
addpath(fullfile(root_dir, 'src'));
addpath(fullfile(root_dir, 'test'));
addpath(fullfile(root_dir, 'test', 'helpers'));

p = 24;
Shape = 'Y43';
factor = 1.5;

nu = p + 1;
nv = 2 * p;
np = nu * nv;
r = zeros(3, np);
nx = zeros(3, np);
xu = zeros(3, np);
xv = zeros(3, np);
w = zeros(np, 1);
[r, nx, xu, xv, w] = build_geometry_bvp_mex(p, np, Shape, r, nx, xu, xv, w);
fprintf('Building matrices for shape=%s, p=%d (size %d x %d)\n', Shape, p, 3*np, 3*np);

SMat = zeros(3*np, 3*np);
SMat = stokesKernelMat_mex(p, np, 3*np, r, w(:), SMat);

% Dirichlet BVP generated by an interior point source
s = struct('x', r, 'nx', nx);
[~, gwt] = gauss(p+1); gwt = gwt';
wt = pi/p * repmat(gwt', 2*p, 1) ./ sin(gl_grid(p));
s.w = (w(:) .* wt(:))';

y_force.x = [0.1; 0.2; -0.3];
y_force.w = 1;
pt_force = [1; 1/2; 1/3];

Ahom = zeros(3*size(s.x, 2), 3*size(y_force.x, 2));
Ahom = Sto3dSLPmat_mex(size(s.x, 2), size(y_force.x, 2), 3*size(s.x, 2), 3*size(y_force.x, 2), ...
  s.x, y_force.x, y_force.w(:), 0, Ahom);
rhs = Ahom * pt_force;
rhs = reshape(rhs, [], 3)';

%% Baseline GMRES solve
b = rhs(:);
gmres_tol = 1e-4;
% gmres_tol = 1e-5; % this tolerance no longer converge
maxit = min(1000, numel(b));
% L = spalloc(3*np, 3*np, 9*np);
% for i = 1:np
%   idx = 3*i-2:3*i;
%   L(idx,idx) = SMat(idx,idx) \ eye(3);
% end
L = speye(3*np); % no need to use the above simple preconditioner, but the accuracy is lower compared to svd...
[mu_gmres, flag_gmres, relres_gmres, iter_gmres, resvec_gmres] = gmres(SMat, b, [], gmres_tol, maxit, @(v) L*v);
fprintf('GMRES: flag=%d, iterations=%d, residual=%.6e\n', flag_gmres, numel(resvec_gmres)-1, relres_gmres);
% evaluate velocity
[s, t, vis] = prepare_bvp_slice(p, r, w, mu_gmres, factor);
u_num = reshape(Sto3dSLPmat_mex(t.n, s.n, 3*t.n, 3*s.n, t.x, s.x, s.w, 0, zeros(3*t.n, 3*s.n)) * s.mu, [], 3)';
u_ref = reshape(Sto3dSLPmat_mex(t.n, 1, 3*t.n, 3, t.x, y_force.x, y_force.w(:), 0, zeros(3*t.n, 3)) * pt_force, [], 3)';
errS = vecnorm(u_num - u_ref) / max(vecnorm(u_ref));
fprintf('GMRES velocity error: max=%.6e, mean=%.6e\n', max(errS), mean(errS));
figure(1); clf; plot_bvp_slice(vis, u_num, errS);

%% Robust solve via truncated SVD
svd_tol = 1e-12;
[U_svd, S_svd, V_svd] = svd(SMat);
diagS = diag(S_svd);
idx = diagS > svd_tol;
mu_svd = V_svd(:,idx) * ((U_svd(:,idx)' * b) ./ diagS(idx));
fprintf('SVD: retained rank=%d, residual=%.6e\n', nnz(idx), norm(SMat*mu_svd-b)/norm(b));
% evaluate velocity
[s, t, vis] = prepare_bvp_slice(p, r, w, mu_svd, factor);
u_num = reshape(Sto3dSLPmat_mex(t.n, s.n, 3*t.n, 3*s.n, t.x, s.x, s.w, 0, zeros(3*t.n, 3*s.n)) * s.mu, [], 3)';
u_ref = reshape(Sto3dSLPmat_mex(t.n, 1, 3*t.n, 3, t.x, y_force.x, y_force.w(:), 0, zeros(3*t.n, 3)) * pt_force, [], 3)';
errS = vecnorm(u_num - u_ref) / max(vecnorm(u_ref));
fprintf('SVD velocity error: max=%.6e, mean=%.6e\n', max(errS), mean(errS));
figure(2); clf; plot_bvp_slice(vis, u_num, errS);

keyboard
