/* --------------------------------------------------- */
/* Automatically generated by mwrap                    */
/* --------------------------------------------------- */

/* Code generated by mwrap 1.2 */
/*
  Copyright statement for mwrap:

  mwrap -- MEX file generation for MATLAB and Octave
  Copyright (c) 2007-2008 David Bindel

  Permission is hereby granted, free of charge, to any person obtaining a copy
  of this software and associated documentation files (the "Software"), to deal
  in the Software without restriction, including without limitation the rights
  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
  copies of the Software, and to permit persons to whom the Software is
  furnished to do so, subject to the following conditions:

  The above copyright notice and this permission notice shall be included in
  all copies or substantial portions of the Software.

  You may distribute a work that contains part or all of the source code
  generated by mwrap under the terms of your choice.

  THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
  IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
  AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
  LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
  OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
  THE SOFTWARE.
*/

#include <stdio.h>
#include <string.h>
#include <stddef.h>

#include <mex.h>

#if MX_HAS_INTERLEAVED_COMPLEX
#include <matrix.h>
#endif


/*
 * Records for call profile.
 */
int* mexprofrecord_= NULL;

double mxWrapGetScalar_char(const mxArray* a, const char** e)
{
    if (!a || mxGetClassID(a) != mxCHAR_CLASS || mxGetM(a)*mxGetN(a) != 1) {
        *e = "Invalid char argument";
        return 0;
    }
    return (char) (*mxGetChars(a));
}

/*
 * Support routines for copying data into and out of the MEX stubs, R2018a
 */

#if MX_HAS_INTERLEAVED_COMPLEX

void* mxWrapGetP(const mxArray* a, const char* fmt, const char** e)
{
    void* p = NULL;
#ifdef R2008OO
    mxArray* ap;
#endif
    if (mxGetClassID(a) == mxDOUBLE_CLASS && mxIsComplex(a) )
    {
        if( mxGetM(a)*mxGetN(a) == 1 && (*mxGetComplexDoubles(a)).real == 0 )
        return NULL;
    }
    if (mxGetClassID(a) == mxDOUBLE_CLASS && !mxIsComplex(a) )
    {
        if( mxGetM(a)*mxGetN(a) == 1 && *mxGetDoubles(a) == 0)
        return NULL;
    }
    if (mxIsChar(a)) {
        char pbuf[128];
        mxGetString(a, pbuf, sizeof(pbuf));
        sscanf(pbuf, fmt, &p);
    } 
#ifdef R2008OO
    else if (ap = mxGetProperty(a, 0, "mwptr")) {
        return mxWrapGetP(ap, fmt, e);
    }
#endif
    if (p == 0)
        *e = "Invalid pointer";
    return p;
}

mxArray* mxWrapCreateP(void* p, const char* fmt)
{
    if (p == 0) {
        mxArray* z = mxCreateDoubleMatrix(1,1, mxREAL);
        *mxGetDoubles(z) = 0;
        return z;
    } else {
        char pbuf[128];
        snprintf(pbuf, sizeof(pbuf), fmt, p);
        return mxCreateString(pbuf);
    }
}

mxArray* mxWrapStrncpy(const char* s)
{
    if (s) {
        return mxCreateString(s);
    } else {
        mxArray* z = mxCreateDoubleMatrix(1,1, mxREAL);
        *mxGetDoubles(z) = 0;
        return z;
    }
}

char* mxWrapGetString(const mxArray* a, const char** e)
{
    char* s;
    mwSize slen;
    if (!a || (!mxIsChar(a) && mxGetM(a)*mxGetN(a) > 0)) {
        *e = "Invalid string argument";
        return NULL;
    }
    slen = mxGetM(a)*mxGetN(a) + 1;
    s = (char*) mxMalloc(slen);
    if (mxGetM(a)*mxGetN(a) == 0)
        *s = 0;
    else
        mxGetString(a, s, slen);
    return s;
}


double mxWrapGetScalar(const mxArray* a, const char** e)
{
    if (!a || mxGetClassID(a) != mxDOUBLE_CLASS || mxGetM(a)*mxGetN(a) != 1) {
        *e = "Invalid scalar argument";
        return 0;
    }
    if( mxIsComplex(a) )
      return (double) (*mxGetComplexDoubles(a)).real;
    else
      return (double) (*mxGetDoubles(a));
}

#define mxWrapGetArrayDef(func, T) \
T* func(const mxArray* a, const char** e)     \
{ \
    T* array; \
    mwSize arraylen; \
    mwIndex i; \
    T* p; \
    double* q; \
    mxComplexDouble* z; \
    if (!a || mxGetClassID(a) != mxDOUBLE_CLASS) { \
        *e = "Invalid array argument, mxDOUBLE_CLASS expected"; \
        return 0; \
    } \
    arraylen = mxGetM(a)*mxGetN(a); \
    array = (T*) mxMalloc(mxGetM(a)*mxGetN(a) * sizeof(T)); \
    p = array; \
    if( mxIsComplex(a) ) \
      { \
	z = mxGetComplexDoubles(a);	   \
	for (i = 0; i < arraylen; ++i)		\
	  *p++ = (T) (*z++).real;			\
      } \
    else \
      {				   \
	q = mxGetDoubles(a);	   \
	for (i = 0; i < arraylen; ++i)		\
	  *p++ = (T) (*q++);			\
      } \
    return array; \
}


#define mxWrapCopyDef(func, T) \
void func(mxArray* a, const T* q, mwSize n) \
{ \
    mwIndex i; \
    double* p;	\
    mxComplexDouble* z; \
    if( mxIsComplex(a) ) \
      { \
	z = mxGetComplexDoubles(a);	   \
	for (i = 0; i < n; ++i)		\
	  (*z++).real = (double) *q++;	\
	  (*z++).imag = 0;	\
      } \
    else \
      {				   \
	p = mxGetDoubles(a);	   \
	for (i = 0; i < n; ++i)		\
	  *p++ = (double) *q++;		\
      } \
}


#define mxWrapReturnDef(func, T) \
mxArray* func(const T* q, mwSize m, mwSize n) \
{ \
    mwIndex i; \
    double* p; \
    if (!q) { \
        return mxCreateDoubleMatrix(0,0, mxREAL); \
    } else { \
        mxArray* a = mxCreateDoubleMatrix(m,n, mxREAL); \
        p = mxGetDoubles(a); \
        for (i = 0; i < m*n; ++i) \
	  *p++ = (double) *q++;	  \
        return a; \
    } \
}


#define mxWrapGetScalarZDef(func, T, ZT, setz)	\
void func(T* z, const mxArray* a) \
{ \
    if( mxIsComplex(a) ) \
      { \
  setz(z, (ZT) (*mxGetComplexDoubles(a)).real, (ZT) (*mxGetComplexDoubles(a)).imag); \
      } \
    else \
      {				   \
  setz(z, (ZT) (*mxGetComplexDoubles(a)).real, (ZT) 0);	\
      } \
}


#define mxWrapGetArrayZDef(func, T, ZT, setz)      \
T* func(const mxArray* a, const char** e)     \
{ \
    T* array; \
    mwSize arraylen; \
    mwIndex i; \
    T* p; \
    double* q; \
    mxComplexDouble* z; \
    if (!a || mxGetClassID(a) != mxDOUBLE_CLASS) { \
        *e = "Invalid array argument, mxDOUBLE_CLASS expected"; \
        return 0; \
    } \
    arraylen = mxGetM(a)*mxGetN(a); \
    array = (T*) mxMalloc(mxGetM(a)*mxGetN(a) * sizeof(T)); \
    p = array; \
    if( mxIsComplex(a) ) \
      { \
	z = mxGetComplexDoubles(a);	   \
	for (i = 0; i < arraylen; ++i) {	\
	  setz(p, (ZT) (*z).real, (ZT) (*z).imag);	\
  	  ++p; ++z; }					\
      } \
    else \
      {				   \
	q = mxGetDoubles(a);	   \
	for (i = 0; i < arraylen; ++i)	{	\
	  setz(p, (ZT) (*q), (ZT) 0 );		\
          ++p; ++q; }			\
      }						\
    return array; \
}


#define mxWrapCopyZDef(func, T, freal, fimag)	    \
void func(mxArray* a, const T* q, mwSize n) \
{ \
    mwIndex i; \
    double* p;	\
    mxComplexDouble* z; \
    if( mxIsComplex(a) ) \
      { \
	z = mxGetComplexDoubles(a);	   \
	for (i = 0; i < n; ++i)	{		\
          (*z).real = freal(*q);			\
	  (*z).imag = fimag(*q);			\
	  ++z; ++q; 	}			\
      } \
    else \
      {				   \
	p = mxGetDoubles(a);	   \
	for (i = 0; i < n; ++i)		\
	  *p++ = freal(*q++);		\
      } \
}


#define mxWrapReturnZDef(func, T, freal, fimag)	      \
mxArray* func(const T* q, mwSize m, mwSize n) \
{ \
    mwIndex i; \
    mxComplexDouble* p; \
    if (!q) { \
        return mxCreateDoubleMatrix(0,0, mxCOMPLEX); \
    } else { \
        mxArray* a = mxCreateDoubleMatrix(m,n, mxCOMPLEX); \
        p = mxGetComplexDoubles(a); \
        for (i = 0; i < m*n; ++i) {	  \
          (*p).real = freal(*q);			\
	  (*p).imag = fimag(*q);			\
	  ++p; ++q; 	}			\
        return a; \
    } \
}






void* mxWrapGetP_single(const mxArray* a, const char* fmt, const char** e)
{
    void* p = NULL;
#ifdef R2008OO
    mxArray* ap;
#endif
    if (mxGetClassID(a) == mxSINGLE_CLASS && mxIsComplex(a) )
    {
        if( mxGetM(a)*mxGetN(a) == 1 && (*mxGetComplexSingles(a)).real == 0 )
        return NULL;
    }
    if (mxGetClassID(a) == mxSINGLE_CLASS && !mxIsComplex(a) )
    {
        if( mxGetM(a)*mxGetN(a) == 1 && *mxGetSingles(a) == 0)
        return NULL;
    }
    if (mxIsChar(a)) {
        char pbuf[128];
        mxGetString(a, pbuf, sizeof(pbuf));
        sscanf(pbuf, fmt, &p);
    } 
#ifdef R2008OO
    else if (ap = mxGetProperty(a, 0, "mwptr")) {
        return mxWrapGetP(ap, fmt, e);
    }
#endif
    if (p == 0)
        *e = "Invalid pointer";
    return p;
}

mxArray* mxWrapCreateP_single(void* p, const char* fmt)
{
    if (p == 0) {
        mxArray* z = mxCreateNumericMatrix(1,1, mxSINGLE_CLASS, mxREAL);
        *mxGetSingles(z) = 0;
        return z;
    } else {
        char pbuf[128];
        snprintf(pbuf, sizeof(pbuf), fmt, p);
        return mxCreateString(pbuf);
    }
}

mxArray* mxWrapStrncpy_single(const char* s)
{
    if (s) {
        return mxCreateString(s);
    } else {
        mxArray* z = mxCreateNumericMatrix(1,1, mxSINGLE_CLASS, mxREAL);
        *mxGetSingles(z) = 0;
        return z;
    }
}

float mxWrapGetScalar_single(const mxArray* a, const char** e)
{
    if (!a || mxGetClassID(a) != mxSINGLE_CLASS || mxGetM(a)*mxGetN(a) != 1) {
        *e = "Invalid scalar argument";
        return 0;
    }
    if( mxIsComplex(a) )
      return (float) (*mxGetComplexSingles(a)).real;
    else
      return (float) (*mxGetSingles(a));
}


char* mxWrapGetString_single(const mxArray* a, const char** e)
{
    char* s;
    mwSize slen;
    if (!a || (!mxIsChar(a) && mxGetM(a)*mxGetN(a) > 0)) {
        *e = "Invalid string argument";
        return NULL;
    }
    slen = mxGetM(a)*mxGetN(a) + 1;
    s = (char*) mxMalloc(slen);
    if (mxGetM(a)*mxGetN(a) == 0)
        *s = 0;
    else
        mxGetString(a, s, slen);
    return s;
}

#define mxWrapGetArrayDef_single(func, T) \
T* func(const mxArray* a, const char** e)     \
{ \
    T* array; \
    mwSize arraylen; \
    mwIndex i; \
    T* p; \
    float* q; \
    mxComplexSingle* z; \
    if (!a || mxGetClassID(a) != mxSINGLE_CLASS) { \
        *e = "Invalid array argument, mxSINGLE_CLASS expected"; \
        return 0; \
    } \
    arraylen = mxGetM(a)*mxGetN(a); \
    array = (T*) mxMalloc(mxGetM(a)*mxGetN(a) * sizeof(T)); \
    p = array; \
    if( mxIsComplex(a) ) \
      { \
	z = mxGetComplexSingles(a);	   \
	for (i = 0; i < arraylen; ++i)		\
	  *p++ = (T) (*z++).real;			\
      } \
    else \
      {				   \
	q = mxGetSingles(a);	   \
	for (i = 0; i < arraylen; ++i)		\
	  *p++ = (T) (*q++);			\
      } \
    return array; \
}


#define mxWrapCopyDef_single(func, T) \
void func(mxArray* a, const T* q, mwSize n) \
{ \
    mwIndex i; \
    float* p;	\
    mxComplexSingle* z; \
    if( mxIsComplex(a) ) \
      { \
	z = mxGetComplexSingles(a);	   \
	for (i = 0; i < n; ++i)		\
	  (*z++).real = (float) *q++;	\
	  (*z++).imag = 0;	\
      } \
    else \
      {				   \
	p = mxGetSingles(a);	   \
	for (i = 0; i < n; ++i)		\
	  *p++ = (float) *q++;		\
      } \
}


#define mxWrapReturnDef_single(func, T) \
mxArray* func(const T* q, mwSize m, mwSize n) \
{ \
    mwIndex i; \
    float* p; \
    if (!q) { \
        return mxCreateNumericMatrix(0,0, mxSINGLE_CLASS, mxREAL); \
    } else { \
        mxArray* a = mxCreateNumericMatrix(m,n, mxSINGLE_CLASS, mxREAL); \
        p = mxGetSingles(a); \
        for (i = 0; i < m*n; ++i) \
	  *p++ = (float) *q++;	  \
        return a; \
    } \
}


#define mxWrapGetScalarZDef_single(func, T, ZT, setz)	\
void func(T* z, const mxArray* a) \
{ \
    if( mxIsComplex(a) ) \
      { \
  setz(z, (ZT) (*mxGetComplexSingles(a)).real, (ZT) (*mxGetComplexSingles(a)).imag); \
      } \
    else \
      {				   \
  setz(z, (ZT) (*mxGetComplexSingles(a)).real, (ZT) 0);	\
      } \
}


#define mxWrapGetArrayZDef_single(func, T, ZT, setz)      \
T* func(const mxArray* a, const char** e)     \
{ \
    T* array; \
    mwSize arraylen; \
    mwIndex i; \
    T* p; \
    float* q; \
    mxComplexSingle* z; \
    if (!a || mxGetClassID(a) != mxSINGLE_CLASS) { \
        *e = "Invalid array argument, mxSINGLE_CLASS expected"; \
        return 0; \
    } \
    arraylen = mxGetM(a)*mxGetN(a); \
    array = (T*) mxMalloc(mxGetM(a)*mxGetN(a) * sizeof(T)); \
    p = array; \
    if( mxIsComplex(a) ) \
      { \
	z = mxGetComplexSingles(a);	   \
	for (i = 0; i < arraylen; ++i) {	\
	  setz(p, (ZT) (*z).real, (ZT) (*z).imag);	\
  	  ++p; ++z; }					\
      } \
    else \
      {				   \
	q = mxGetSingles(a);	   \
	for (i = 0; i < arraylen; ++i)	{	\
	  setz(p, (ZT) (*q), (ZT) 0 );		\
          ++p; ++q; }			\
      }						\
    return array; \
}


#define mxWrapCopyZDef_single(func, T, freal, fimag)	    \
void func(mxArray* a, const T* q, mwSize n) \
{ \
    mwIndex i; \
    float* p;	\
    mxComplexSingle* z; \
    if( mxIsComplex(a) ) \
      { \
	z = mxGetComplexSingles(a);	   \
	for (i = 0; i < n; ++i)	{		\
          (*z).real = freal(*q);			\
	  (*z).imag = fimag(*q);			\
	  ++z; ++q; 	}			\
      } \
    else \
      {				   \
	p = mxGetSingles(a);	   \
	for (i = 0; i < n; ++i)		\
	  *p++ = freal(*q++);		\
      } \
}


#define mxWrapReturnZDef_single(func, T, freal, fimag)	      \
mxArray* func(const T* q, mwSize m, mwSize n) \
{ \
    mwIndex i; \
    mxComplexSingle* p; \
    if (!q) { \
        return mxCreateNumericMatrix(0,0, mxSINGLE_CLASS, mxCOMPLEX); \
    } else { \
        mxArray* a = mxCreateNumericMatrix(m,n, mxSINGLE_CLASS, mxCOMPLEX); \
        p = mxGetComplexSingles(a); \
        for (i = 0; i < m*n; ++i) {	  \
          (*p).real = freal(*q);			\
	  (*p).imag = fimag(*q);			\
	  ++p; ++q; 	}			\
        return a; \
    } \
}



#else

/*
 * Support routines for copying data into and out of the MEX stubs, -R2017b
 */

void* mxWrapGetP(const mxArray* a, const char* fmt, const char** e)
{
    void* p = 0;
#ifdef R2008OO
    mxArray* ap;
#endif
    if (mxGetClassID(a) == mxDOUBLE_CLASS && 
        mxGetM(a)*mxGetN(a) == 1 && *mxGetPr(a) == 0)
        return p;
    if (mxIsChar(a)) {
        char pbuf[128];
        mxGetString(a, pbuf, sizeof(pbuf));
        sscanf(pbuf, fmt, &p);
    } 
#ifdef R2008OO
    else if (ap = mxGetProperty(a, 0, "mwptr")) {
        return mxWrapGetP(ap, fmt, e);
    }
#endif
    if (p == 0)
        *e = "Invalid pointer";
    return p;
}

mxArray* mxWrapCreateP(void* p, const char* fmt)
{
    if (p == 0) {
        mxArray* z = mxCreateDoubleMatrix(1,1, mxREAL);
        *mxGetPr(z) = 0;
        return z;
    } else {
        char pbuf[128];
        snprintf(pbuf, sizeof(pbuf), fmt, p);
        return mxCreateString(pbuf);
    }
}

mxArray* mxWrapStrncpy(const char* s)
{
    if (s) {
        return mxCreateString(s);
    } else {
        mxArray* z = mxCreateDoubleMatrix(1,1, mxREAL);
        *mxGetPr(z) = 0;
        return z;
    }
}

double mxWrapGetScalar(const mxArray* a, const char** e)
{
    if (!a || mxGetClassID(a) != mxDOUBLE_CLASS || mxGetM(a)*mxGetN(a) != 1) {
        *e = "Invalid scalar argument";
        return 0;
    }
    return *mxGetPr(a);
}

char* mxWrapGetString(const mxArray* a, const char** e)
{
    char* s;
    mwSize slen;
    if (!a || (!mxIsChar(a) && mxGetM(a)*mxGetN(a) > 0)) {
        *e = "Invalid string argument";
        return NULL;
    }
    slen = mxGetM(a)*mxGetN(a) + 1;
    s = (char*) mxMalloc(slen);
    if (mxGetM(a)*mxGetN(a) == 0)
        *s = 0;
    else
        mxGetString(a, s, slen);
    return s;
}


#define mxWrapGetArrayDef(func, T) \
T* func(const mxArray* a, const char** e)     \
{ \
    T* array; \
    mwSize arraylen; \
    mwIndex i; \
    T* p; \
    double* q; \
    if (!a || mxGetClassID(a) != mxDOUBLE_CLASS) { \
        *e = "Invalid array argument, mxDOUBLE_CLASS expected"; \
        return 0; \
    } \
    arraylen = mxGetM(a)*mxGetN(a); \
    array = (T*) mxMalloc(mxGetM(a)*mxGetN(a) * sizeof(T)); \
    p = array; \
    q = mxGetPr(a); \
    for (i = 0; i < arraylen; ++i) \
        *p++ = (T) (*q++); \
    return array; \
}


#define mxWrapCopyDef(func, T) \
void func(mxArray* a, const T* q, mwSize n) \
{ \
    mwIndex i; \
    double* p = mxGetPr(a); \
    for (i = 0; i < n; ++i) \
        *p++ = *q++; \
}


#define mxWrapReturnDef(func, T) \
mxArray* func(const T* q, mwSize m, mwSize n) \
{ \
    mwIndex i; \
    double* p; \
    if (!q) { \
        return mxCreateDoubleMatrix(0,0, mxREAL); \
    } else { \
        mxArray* a = mxCreateDoubleMatrix(m,n, mxREAL); \
        p = mxGetPr(a); \
        for (i = 0; i < m*n; ++i) \
            *p++ = *q++; \
        return a; \
    } \
}


#define mxWrapGetScalarZDef(func, T, ZT, setz) \
void func(T* z, const mxArray* a) \
{ \
    double* pr = mxGetPr(a); \
    double* pi = mxGetPi(a); \
    setz(z, (ZT) *pr, (pi ? (ZT) *pi : (ZT) 0)); \
}


#define mxWrapGetArrayZDef(func, T, ZT, setz) \
T* func(const mxArray* a, const char** e) \
{ \
    T* array; \
    mwSize arraylen; \
    mwIndex i; \
    T* p; \
    double* qr; \
    double* qi; \
    if (!a || mxGetClassID(a) != mxDOUBLE_CLASS) { \
        *e = "Invalid array argument, mxDOUBLE_CLASS expected"; \
        return 0; \
    } \
    arraylen = mxGetM(a)*mxGetN(a); \
    array = (T*) mxMalloc(mxGetM(a)*mxGetN(a) * sizeof(T)); \
    p = array; \
    qr = mxGetPr(a); \
    qi = mxGetPi(a); \
    for (i = 0; i < arraylen; ++i) { \
        ZT val_qr = *qr++; \
        ZT val_qi = (qi ? (ZT) *qi++ : (ZT) 0); \
        setz(p, val_qr, val_qi); \
        ++p; \
    } \
    return array; \
}


#define mxWrapCopyZDef(func, T, real, imag) \
void func(mxArray* a, const T* q, mwSize n) \
{ \
    mwIndex i; \
    double* pr = mxGetPr(a); \
    double* pi = mxGetPi(a); \
    for (i = 0; i < n; ++i) { \
        *pr++ = real(*q); \
        *pi++ = imag(*q); \
        ++q; \
    } \
}


#define mxWrapReturnZDef(func, T, real, imag) \
mxArray* func(const T* q, mwSize m, mwSize n) \
{ \
    mwIndex i; \
    double* pr; \
    double* pi; \
    if (!q) { \
        return mxCreateDoubleMatrix(0,0, mxCOMPLEX); \
    } else { \
        mxArray* a = mxCreateDoubleMatrix(m,n, mxCOMPLEX); \
        pr = mxGetPr(a); \
        pi = mxGetPi(a); \
        for (i = 0; i < m*n; ++i) { \
            *pr++ = real(*q); \
            *pi++ = imag(*q); \
            ++q; \
        } \
        return a; \
    } \
}






void* mxWrapGetP_single(const mxArray* a, const char* fmt, const char** e)
{
    void* p = 0;
#ifdef R2008OO
    mxArray* ap;
#endif
    if (mxGetClassID(a) == mxSINGLE_CLASS && 
        mxGetM(a)*mxGetN(a) == 1 && *((float*)mxGetData(a)) == 0)
        return p;
    if (mxIsChar(a)) {
        char pbuf[128];
        mxGetString(a, pbuf, sizeof(pbuf));
        sscanf(pbuf, fmt, &p);
    } 
#ifdef R2008OO
    else if (ap = mxGetProperty(a, 0, "mwptr")) {
        return mxWrapGetP(ap, fmt, e);
    }
#endif
    if (p == 0)
        *e = "Invalid pointer";
    return p;
}

mxArray* mxWrapCreateP_single(void* p, const char* fmt)
{
    if (p == 0) {
        mxArray* z = mxCreateNumericMatrix(1,1, mxSINGLE_CLASS, mxREAL);
        *((float*)mxGetData(z)) = 0;
        return z;
    } else {
        char pbuf[128];
        snprintf(pbuf, sizeof(pbuf), fmt, p);
        return mxCreateString(pbuf);
    }
}
mxArray* mxWrapStrncpy_single(const char* s)
{
    if (s) {
        return mxCreateString(s);
    } else {
        mxArray* z = mxCreateNumericMatrix(1,1, mxSINGLE_CLASS, mxREAL);
        *((float*)mxGetData(z)) = 0;
        return z;
    }
}

float mxWrapGetScalar_single(const mxArray* a, const char** e)
{
    if (!a || mxGetClassID(a) != mxSINGLE_CLASS || mxGetM(a)*mxGetN(a) != 1) {
        *e = "Invalid scalar argument";
        return 0;
    }
    return *((float*)mxGetData(a));
}

char* mxWrapGetString_single(const mxArray* a, const char** e)
{
    char* s;
    mwSize slen;
    if (!a || (!mxIsChar(a) && mxGetM(a)*mxGetN(a) > 0)) {
        *e = "Invalid string argument, mxSINGLE_CLASS expected";
        return NULL;
    }
    slen = mxGetM(a)*mxGetN(a) + 1;
    s = (char*) mxMalloc(slen);
    if (mxGetM(a)*mxGetN(a) == 0)
        *s = 0;
    else
        mxGetString(a, s, slen);
    return s;
}


#define mxWrapGetArrayDef_single(func, T) \
T* func(const mxArray* a, const char** e)     \
{ \
    T* array; \
    mwSize arraylen; \
    mwIndex i; \
    T* p; \
    float* q; \
    if (!a || mxGetClassID(a) != mxSINGLE_CLASS) { \
        *e = "Invalid array argument, mxSINGLE_CLASS expected"; \
        return 0; \
    } \
    arraylen = mxGetM(a)*mxGetN(a); \
    array = (T*) mxMalloc(mxGetM(a)*mxGetN(a) * sizeof(T)); \
    p = array; \
    q = (float*) mxGetData(a);	   \
    for (i = 0; i < arraylen; ++i) \
        *p++ = (T) (*q++); \
    return array; \
}


#define mxWrapCopyDef_single(func, T) \
void func(mxArray* a, const T* q, mwSize n) \
{ \
    mwIndex i; \
    float* p = (float*) mxGetData(a);		\
    for (i = 0; i < n; ++i) \
        *p++ = *q++; \
}


#define mxWrapReturnDef_single(func, T) \
mxArray* func(const T* q, mwSize m, mwSize n) \
{ \
    mwIndex i; \
    float* p; \
    if (!q) { \
      return mxCreateNumericMatrix(0,0, mxSINGLE_CLASS, mxREAL); \
    } else { \
        mxArray* a = mxCreateNumericMatrix(m,n, mxSINGLE_CLASS, mxREAL);\
        p = (float*) mxGetData(a);				\
        for (i = 0; i < m*n; ++i) \
            *p++ = *q++; \
        return a; \
    } \
}


#define mxWrapGetScalarZDef_single(func, T, ZT, setz) \
void func(T* z, const mxArray* a) \
{ \
    float* pr = (float*) mxGetData(a);		\
    float* pi = (float*) mxGetImagData(a);		 \
    setz(z, (ZT) *pr, (pi ? (ZT) *pi : (ZT) 0)); \
}


#define mxWrapGetArrayZDef_single(func, T, ZT, setz) \
T* func(const mxArray* a, const char** e) \
{ \
    T* array; \
    mwSize arraylen; \
    mwIndex i; \
    T* p; \
    float* qr; \
    float* qi; \
    if (!a || mxGetClassID(a) != mxSINGLE_CLASS) { \
        *e = "Invalid array argument, mxSINGLE_CLASS expected"; \
        return 0; \
    } \
    arraylen = mxGetM(a)*mxGetN(a); \
    array = (T*) mxMalloc(mxGetM(a)*mxGetN(a) * sizeof(T)); \
    p = array; \
    qr = (float*) mxGetData(a);			\
    qi = (float*) mxGetImagData(a);			\
    for (i = 0; i < arraylen; ++i) { \
        ZT val_qr = *qr++; \
        ZT val_qi = (qi ? (ZT) *qi++ : (ZT) 0); \
        setz(p, val_qr, val_qi); \
        ++p; \
    } \
    return array; \
}


#define mxWrapCopyZDef_single(func, T, real, imag) \
void func(mxArray* a, const T* q, mwSize n) \
{ \
    mwIndex i; \
    float* pr = (float*) mxGetData(a);		\
    float* pi = (float*) mxGetImagData(a);		\
    for (i = 0; i < n; ++i) { \
        *pr++ = real(*q); \
        *pi++ = imag(*q); \
        ++q; \
    } \
}


#define mxWrapReturnZDef_single(func, T, real, imag) \
mxArray* func(const T* q, mwSize m, mwSize n) \
{ \
    mwIndex i; \
    float* pr; \
    float* pi; \
    if (!q) { \
      return mxCreateNumericMatrix(0,0, mxSINGLE_CLASS, mxCOMPLEX); \
    } else { \
        mxArray* a = mxCreateNumericMatrix(m,n, mxSINGLE_CLASS, mxCOMPLEX);\
        pr = (float*) mxGetData(a);					\
        pi = (float*) mxGetImagData(a);					\
        for (i = 0; i < m*n; ++i) { \
            *pr++ = real(*q); \
            *pi++ = imag(*q); \
            ++q; \
        } \
        return a; \
    } \
}





#endif

#include <complex.h>

typedef _Complex double dcomplex;
#define real_dcomplex(z) creal(z)
#define imag_dcomplex(z) cimag(z)
#define setz_dcomplex(z,r,i)  *z = r + i*_Complex_I

typedef _Complex float fcomplex;
#define real_fcomplex(z) crealf(z)
#define imag_fcomplex(z) cimagf(z)
#define setz_fcomplex(z,r,i)  *z = r + i*_Complex_I




/* Array copier definitions */
mxWrapGetArrayDef(mxWrapGetArray_bool, bool)
mxWrapCopyDef    (mxWrapCopy_bool,     bool)
mxWrapReturnDef  (mxWrapReturn_bool,   bool)
mxWrapGetArrayDef_single(mxWrapGetArray_single_bool, bool)
mxWrapCopyDef_single    (mxWrapCopy_single_bool,     bool)
mxWrapReturnDef_single  (mxWrapReturn_single_bool,   bool)
mxWrapGetArrayDef(mxWrapGetArray_char, char)
mxWrapCopyDef    (mxWrapCopy_char,     char)
mxWrapReturnDef  (mxWrapReturn_char,   char)
mxWrapGetArrayDef_single(mxWrapGetArray_single_char, char)
mxWrapCopyDef_single    (mxWrapCopy_single_char,     char)
mxWrapReturnDef_single  (mxWrapReturn_single_char,   char)
mxWrapGetArrayDef(mxWrapGetArray_double, double)
mxWrapCopyDef    (mxWrapCopy_double,     double)
mxWrapReturnDef  (mxWrapReturn_double,   double)
mxWrapGetArrayDef_single(mxWrapGetArray_single_double, double)
mxWrapCopyDef_single    (mxWrapCopy_single_double,     double)
mxWrapReturnDef_single  (mxWrapReturn_single_double,   double)
mxWrapGetArrayDef(mxWrapGetArray_float, float)
mxWrapCopyDef    (mxWrapCopy_float,     float)
mxWrapReturnDef  (mxWrapReturn_float,   float)
mxWrapGetArrayDef_single(mxWrapGetArray_single_float, float)
mxWrapCopyDef_single    (mxWrapCopy_single_float,     float)
mxWrapReturnDef_single  (mxWrapReturn_single_float,   float)
mxWrapGetArrayDef(mxWrapGetArray_int, int)
mxWrapCopyDef    (mxWrapCopy_int,     int)
mxWrapReturnDef  (mxWrapReturn_int,   int)
mxWrapGetArrayDef_single(mxWrapGetArray_single_int, int)
mxWrapCopyDef_single    (mxWrapCopy_single_int,     int)
mxWrapReturnDef_single  (mxWrapReturn_single_int,   int)
mxWrapGetArrayDef(mxWrapGetArray_long, long)
mxWrapCopyDef    (mxWrapCopy_long,     long)
mxWrapReturnDef  (mxWrapReturn_long,   long)
mxWrapGetArrayDef_single(mxWrapGetArray_single_long, long)
mxWrapCopyDef_single    (mxWrapCopy_single_long,     long)
mxWrapReturnDef_single  (mxWrapReturn_single_long,   long)
mxWrapGetArrayDef(mxWrapGetArray_ptrdiff_t, ptrdiff_t)
mxWrapCopyDef    (mxWrapCopy_ptrdiff_t,     ptrdiff_t)
mxWrapReturnDef  (mxWrapReturn_ptrdiff_t,   ptrdiff_t)
mxWrapGetArrayDef_single(mxWrapGetArray_single_ptrdiff_t, ptrdiff_t)
mxWrapCopyDef_single    (mxWrapCopy_single_ptrdiff_t,     ptrdiff_t)
mxWrapReturnDef_single  (mxWrapReturn_single_ptrdiff_t,   ptrdiff_t)
mxWrapGetArrayDef(mxWrapGetArray_short, short)
mxWrapCopyDef    (mxWrapCopy_short,     short)
mxWrapReturnDef  (mxWrapReturn_short,   short)
mxWrapGetArrayDef_single(mxWrapGetArray_single_short, short)
mxWrapCopyDef_single    (mxWrapCopy_single_short,     short)
mxWrapReturnDef_single  (mxWrapReturn_single_short,   short)
mxWrapGetArrayDef(mxWrapGetArray_size_t, size_t)
mxWrapCopyDef    (mxWrapCopy_size_t,     size_t)
mxWrapReturnDef  (mxWrapReturn_size_t,   size_t)
mxWrapGetArrayDef_single(mxWrapGetArray_single_size_t, size_t)
mxWrapCopyDef_single    (mxWrapCopy_single_size_t,     size_t)
mxWrapReturnDef_single  (mxWrapReturn_single_size_t,   size_t)
mxWrapGetScalarZDef(mxWrapGetScalar_fcomplex, fcomplex,
                    float, setz_fcomplex)
mxWrapGetArrayZDef (mxWrapGetArray_fcomplex, fcomplex,
                    float, setz_fcomplex)
mxWrapCopyZDef     (mxWrapCopy_fcomplex, fcomplex,
                    real_fcomplex, imag_fcomplex)
mxWrapReturnZDef   (mxWrapReturn_fcomplex, fcomplex,
                    real_fcomplex, imag_fcomplex)
mxWrapGetScalarZDef_single(mxWrapGetScalar_single_fcomplex, fcomplex,
                    float, setz_fcomplex)
mxWrapGetArrayZDef_single (mxWrapGetArray_single_fcomplex, fcomplex,
                    float, setz_fcomplex)
mxWrapCopyZDef_single     (mxWrapCopy_single_fcomplex, fcomplex,
                    real_fcomplex, imag_fcomplex)
mxWrapReturnZDef_single   (mxWrapReturn_single_fcomplex, fcomplex,
                    real_fcomplex, imag_fcomplex)
mxWrapGetScalarZDef(mxWrapGetScalar_dcomplex, dcomplex,
                    double, setz_dcomplex)
mxWrapGetArrayZDef (mxWrapGetArray_dcomplex, dcomplex,
                    double, setz_dcomplex)
mxWrapCopyZDef     (mxWrapCopy_dcomplex, dcomplex,
                    real_dcomplex, imag_dcomplex)
mxWrapReturnZDef   (mxWrapReturn_dcomplex, dcomplex,
                    real_dcomplex, imag_dcomplex)
mxWrapGetScalarZDef_single(mxWrapGetScalar_single_dcomplex, dcomplex,
                    double, setz_dcomplex)
mxWrapGetArrayZDef_single (mxWrapGetArray_single_dcomplex, dcomplex,
                    double, setz_dcomplex)
mxWrapCopyZDef_single     (mxWrapCopy_single_dcomplex, dcomplex,
                    real_dcomplex, imag_dcomplex)
mxWrapReturnZDef_single   (mxWrapReturn_single_dcomplex, dcomplex,
                    real_dcomplex, imag_dcomplex)

#if defined(MWF77_CAPS)
#define MWF77_stokesKernelMat_mex STOKESKERNELMAT_MEX
#define MWF77_Sto3dSLPmat_mex STO3DSLPMAT_MEX
#define MWF77_Sto3dSLPnmat_mex STO3DSLPNMAT_MEX
#define MWF77_build_geometry_bvp_mex BUILD_GEOMETRY_BVP_MEX
#define MWF77_kerneldSMatrix_mex KERNELDSMATRIX_MEX
#define MWF77_sht_ana_rotgrid_mex SHT_ANA_ROTGRID_MEX
#define MWF77_ynm_all_mex YNM_ALL_MEX
#elif defined(MWF77_UNDERSCORE1)
#define MWF77_stokesKernelMat_mex stokeskernelmat_mex_
#define MWF77_Sto3dSLPmat_mex sto3dslpmat_mex_
#define MWF77_Sto3dSLPnmat_mex sto3dslpnmat_mex_
#define MWF77_build_geometry_bvp_mex build_geometry_bvp_mex_
#define MWF77_kerneldSMatrix_mex kerneldsmatrix_mex_
#define MWF77_sht_ana_rotgrid_mex sht_ana_rotgrid_mex_
#define MWF77_ynm_all_mex ynm_all_mex_
#elif defined(MWF77_UNDERSCORE0)
#define MWF77_stokesKernelMat_mex stokeskernelmat_mex
#define MWF77_Sto3dSLPmat_mex sto3dslpmat_mex
#define MWF77_Sto3dSLPnmat_mex sto3dslpnmat_mex
#define MWF77_build_geometry_bvp_mex build_geometry_bvp_mex
#define MWF77_kerneldSMatrix_mex kerneldsmatrix_mex
#define MWF77_sht_ana_rotgrid_mex sht_ana_rotgrid_mex
#define MWF77_ynm_all_mex ynm_all_mex
#else /* f2c convention */
#define MWF77_stokesKernelMat_mex stokeskernelmat_mex__
#define MWF77_Sto3dSLPmat_mex sto3dslpmat_mex__
#define MWF77_Sto3dSLPnmat_mex sto3dslpnmat_mex__
#define MWF77_build_geometry_bvp_mex build_geometry_bvp_mex__
#define MWF77_kerneldSMatrix_mex kerneldsmatrix_mex__
#define MWF77_sht_ana_rotgrid_mex sht_ana_rotgrid_mex__
#define MWF77_ynm_all_mex ynm_all_mex__
#endif

#ifdef __cplusplus
extern "C" { /* Prevent C++ name mangling */
#endif

#ifndef MWF77_RETURN
#define MWF77_RETURN int
#endif

MWF77_RETURN MWF77_stokesKernelMat_mex(int*, int*, int*, double*, double*, double*);
MWF77_RETURN MWF77_Sto3dSLPmat_mex(int*, int*, int*, int*, double*, double*, double*, int*, double*);
MWF77_RETURN MWF77_Sto3dSLPnmat_mex(int*, int*, int*, int*, double*, double*, double*, double*, int*, double*);
MWF77_RETURN MWF77_build_geometry_bvp_mex(int*, int*, char*, int*, double*, double*, double*, double*, double*);
MWF77_RETURN MWF77_kerneldSMatrix_mex(int*, int*, int*, double*, double*, double*, double*);
MWF77_RETURN MWF77_sht_ana_rotgrid_mex(int*, int*, int*, double*, int*, dcomplex*);
MWF77_RETURN MWF77_ynm_all_mex(int*, int*, int*, double*, double*, dcomplex*);

#ifdef __cplusplus
} /* end extern C */
#endif

/* ---- matlab/stokes.mw: 2 ----
 * stokesKernelMat_mex(int[1] p, int[1] n, int[1] n3, double[3, n] rxyz, double[n] w, inout double[n3, n3] A);
 */
static const char* stubids1_ = "stokesKernelMat_mex(c i int[x], c i int[x], c i int[x], c i double[xx], c i double[x], c io double[xx])";

void mexStub1(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    int*        in0_ =0; /* p          */
    int*        in1_ =0; /* n          */
    int*        in2_ =0; /* n3         */
    double*     in3_ =0; /* rxyz       */
    double*     in4_ =0; /* w          */
    double*     in5_ =0; /* A          */
    mwSize      dim6_;   /* 1          */
    mwSize      dim7_;   /* 1          */
    mwSize      dim8_;   /* 1          */
    mwSize      dim9_;   /* 3          */
    mwSize      dim10_;   /* n          */
    mwSize      dim11_;   /* n          */
    mwSize      dim12_;   /* n3         */
    mwSize      dim13_;   /* n3         */

    dim6_ = (mwSize) mxWrapGetScalar(prhs[6], &mw_err_txt_);
    dim7_ = (mwSize) mxWrapGetScalar(prhs[7], &mw_err_txt_);
    dim8_ = (mwSize) mxWrapGetScalar(prhs[8], &mw_err_txt_);
    dim9_ = (mwSize) mxWrapGetScalar(prhs[9], &mw_err_txt_);
    dim10_ = (mwSize) mxWrapGetScalar(prhs[10], &mw_err_txt_);
    dim11_ = (mwSize) mxWrapGetScalar(prhs[11], &mw_err_txt_);
    dim12_ = (mwSize) mxWrapGetScalar(prhs[12], &mw_err_txt_);
    dim13_ = (mwSize) mxWrapGetScalar(prhs[13], &mw_err_txt_);

    if (mxGetM(prhs[0])*mxGetN(prhs[0]) != dim6_) {
        mw_err_txt_ = "Bad argument size: p";        goto mw_err_label;
    }

    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != dim7_) {
        mw_err_txt_ = "Bad argument size: n";        goto mw_err_label;
    }

    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != dim8_) {
        mw_err_txt_ = "Bad argument size: n3";        goto mw_err_label;
    }

    if (mxGetM(prhs[3]) != dim9_ ||
        mxGetN(prhs[3]) != dim10_) {
        mw_err_txt_ = "Bad argument size: rxyz";
        goto mw_err_label;
    }

    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != dim11_) {
        mw_err_txt_ = "Bad argument size: w";        goto mw_err_label;
    }

    if (mxGetM(prhs[5]) != dim12_ ||
        mxGetN(prhs[5]) != dim13_) {
        mw_err_txt_ = "Bad argument size: A";
        goto mw_err_label;
    }

    if (mxGetM(prhs[0])*mxGetN(prhs[0]) != 0) {
        in0_ = mxWrapGetArray_int(prhs[0], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in0_ = NULL;

    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != 0) {
        in1_ = mxWrapGetArray_int(prhs[1], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in1_ = NULL;

    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != 0) {
        in2_ = mxWrapGetArray_int(prhs[2], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in2_ = NULL;

    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != 0) {
        if( mxGetClassID(prhs[3]) != mxDOUBLE_CLASS )
            mw_err_txt_ = "Invalid array argument, mxDOUBLE_CLASS expected";
        if (mw_err_txt_) goto mw_err_label;
#if MX_HAS_INTERLEAVED_COMPLEX
        in3_ = mxGetDoubles(prhs[3]);
#else
        in3_ = mxGetPr(prhs[3]);
#endif
    } else
        in3_ = NULL;

    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != 0) {
        if( mxGetClassID(prhs[4]) != mxDOUBLE_CLASS )
            mw_err_txt_ = "Invalid array argument, mxDOUBLE_CLASS expected";
        if (mw_err_txt_) goto mw_err_label;
#if MX_HAS_INTERLEAVED_COMPLEX
        in4_ = mxGetDoubles(prhs[4]);
#else
        in4_ = mxGetPr(prhs[4]);
#endif
    } else
        in4_ = NULL;

    if (mxGetM(prhs[5])*mxGetN(prhs[5]) != 0) {
        in5_ = mxWrapGetArray_double(prhs[5], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in5_ = NULL;

    if (mexprofrecord_)
        mexprofrecord_[1]++;
    MWF77_stokesKernelMat_mex(in0_, in1_, in2_, in3_, in4_, in5_);
    plhs[0] = mxCreateDoubleMatrix(dim12_, dim13_, mxREAL);
    mxWrapCopy_double(plhs[0], in5_, dim12_*dim13_);

mw_err_label:
    if (in0_)  mxFree(in0_);
    if (in1_)  mxFree(in1_);
    if (in2_)  mxFree(in2_);
    if (in5_)  mxFree(in5_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ---- matlab/stokes.mw: 4 ----
 * Sto3dSLPmat_mex(int[1] nt, int[1] ns, int[1] nt3, int[1] ns3, double[3, nt] xt, double[3, ns] xs, double[ns] ws, int[1] if_self, inout double[nt3, ns3] A);
 */
static const char* stubids2_ = "Sto3dSLPmat_mex(c i int[x], c i int[x], c i int[x], c i int[x], c i double[xx], c i double[xx], c i double[x], c i int[x], c io double[xx])";

void mexStub2(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    int*        in0_ =0; /* nt         */
    int*        in1_ =0; /* ns         */
    int*        in2_ =0; /* nt3        */
    int*        in3_ =0; /* ns3        */
    double*     in4_ =0; /* xt         */
    double*     in5_ =0; /* xs         */
    double*     in6_ =0; /* ws         */
    int*        in7_ =0; /* if_self    */
    double*     in8_ =0; /* A          */
    mwSize      dim9_;   /* 1          */
    mwSize      dim10_;   /* 1          */
    mwSize      dim11_;   /* 1          */
    mwSize      dim12_;   /* 1          */
    mwSize      dim13_;   /* 3          */
    mwSize      dim14_;   /* nt         */
    mwSize      dim15_;   /* 3          */
    mwSize      dim16_;   /* ns         */
    mwSize      dim17_;   /* ns         */
    mwSize      dim18_;   /* 1          */
    mwSize      dim19_;   /* nt3        */
    mwSize      dim20_;   /* ns3        */

    dim9_ = (mwSize) mxWrapGetScalar(prhs[9], &mw_err_txt_);
    dim10_ = (mwSize) mxWrapGetScalar(prhs[10], &mw_err_txt_);
    dim11_ = (mwSize) mxWrapGetScalar(prhs[11], &mw_err_txt_);
    dim12_ = (mwSize) mxWrapGetScalar(prhs[12], &mw_err_txt_);
    dim13_ = (mwSize) mxWrapGetScalar(prhs[13], &mw_err_txt_);
    dim14_ = (mwSize) mxWrapGetScalar(prhs[14], &mw_err_txt_);
    dim15_ = (mwSize) mxWrapGetScalar(prhs[15], &mw_err_txt_);
    dim16_ = (mwSize) mxWrapGetScalar(prhs[16], &mw_err_txt_);
    dim17_ = (mwSize) mxWrapGetScalar(prhs[17], &mw_err_txt_);
    dim18_ = (mwSize) mxWrapGetScalar(prhs[18], &mw_err_txt_);
    dim19_ = (mwSize) mxWrapGetScalar(prhs[19], &mw_err_txt_);
    dim20_ = (mwSize) mxWrapGetScalar(prhs[20], &mw_err_txt_);

    if (mxGetM(prhs[0])*mxGetN(prhs[0]) != dim9_) {
        mw_err_txt_ = "Bad argument size: nt";        goto mw_err_label;
    }

    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != dim10_) {
        mw_err_txt_ = "Bad argument size: ns";        goto mw_err_label;
    }

    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != dim11_) {
        mw_err_txt_ = "Bad argument size: nt3";        goto mw_err_label;
    }

    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != dim12_) {
        mw_err_txt_ = "Bad argument size: ns3";        goto mw_err_label;
    }

    if (mxGetM(prhs[4]) != dim13_ ||
        mxGetN(prhs[4]) != dim14_) {
        mw_err_txt_ = "Bad argument size: xt";
        goto mw_err_label;
    }

    if (mxGetM(prhs[5]) != dim15_ ||
        mxGetN(prhs[5]) != dim16_) {
        mw_err_txt_ = "Bad argument size: xs";
        goto mw_err_label;
    }

    if (mxGetM(prhs[6])*mxGetN(prhs[6]) != dim17_) {
        mw_err_txt_ = "Bad argument size: ws";        goto mw_err_label;
    }

    if (mxGetM(prhs[7])*mxGetN(prhs[7]) != dim18_) {
        mw_err_txt_ = "Bad argument size: if_self";        goto mw_err_label;
    }

    if (mxGetM(prhs[8]) != dim19_ ||
        mxGetN(prhs[8]) != dim20_) {
        mw_err_txt_ = "Bad argument size: A";
        goto mw_err_label;
    }

    if (mxGetM(prhs[0])*mxGetN(prhs[0]) != 0) {
        in0_ = mxWrapGetArray_int(prhs[0], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in0_ = NULL;

    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != 0) {
        in1_ = mxWrapGetArray_int(prhs[1], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in1_ = NULL;

    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != 0) {
        in2_ = mxWrapGetArray_int(prhs[2], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in2_ = NULL;

    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != 0) {
        in3_ = mxWrapGetArray_int(prhs[3], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in3_ = NULL;

    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != 0) {
        if( mxGetClassID(prhs[4]) != mxDOUBLE_CLASS )
            mw_err_txt_ = "Invalid array argument, mxDOUBLE_CLASS expected";
        if (mw_err_txt_) goto mw_err_label;
#if MX_HAS_INTERLEAVED_COMPLEX
        in4_ = mxGetDoubles(prhs[4]);
#else
        in4_ = mxGetPr(prhs[4]);
#endif
    } else
        in4_ = NULL;

    if (mxGetM(prhs[5])*mxGetN(prhs[5]) != 0) {
        if( mxGetClassID(prhs[5]) != mxDOUBLE_CLASS )
            mw_err_txt_ = "Invalid array argument, mxDOUBLE_CLASS expected";
        if (mw_err_txt_) goto mw_err_label;
#if MX_HAS_INTERLEAVED_COMPLEX
        in5_ = mxGetDoubles(prhs[5]);
#else
        in5_ = mxGetPr(prhs[5]);
#endif
    } else
        in5_ = NULL;

    if (mxGetM(prhs[6])*mxGetN(prhs[6]) != 0) {
        if( mxGetClassID(prhs[6]) != mxDOUBLE_CLASS )
            mw_err_txt_ = "Invalid array argument, mxDOUBLE_CLASS expected";
        if (mw_err_txt_) goto mw_err_label;
#if MX_HAS_INTERLEAVED_COMPLEX
        in6_ = mxGetDoubles(prhs[6]);
#else
        in6_ = mxGetPr(prhs[6]);
#endif
    } else
        in6_ = NULL;

    if (mxGetM(prhs[7])*mxGetN(prhs[7]) != 0) {
        in7_ = mxWrapGetArray_int(prhs[7], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in7_ = NULL;

    if (mxGetM(prhs[8])*mxGetN(prhs[8]) != 0) {
        in8_ = mxWrapGetArray_double(prhs[8], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in8_ = NULL;

    if (mexprofrecord_)
        mexprofrecord_[2]++;
    MWF77_Sto3dSLPmat_mex(in0_, in1_, in2_, in3_, in4_, in5_, in6_, in7_, in8_);
    plhs[0] = mxCreateDoubleMatrix(dim19_, dim20_, mxREAL);
    mxWrapCopy_double(plhs[0], in8_, dim19_*dim20_);

mw_err_label:
    if (in0_)  mxFree(in0_);
    if (in1_)  mxFree(in1_);
    if (in2_)  mxFree(in2_);
    if (in3_)  mxFree(in3_);
    if (in7_)  mxFree(in7_);
    if (in8_)  mxFree(in8_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ---- matlab/stokes.mw: 6 ----
 * Sto3dSLPnmat_mex(int[1] nt, int[1] ns, int[1] nt3, int[1] ns3, double[3, nt] xt, double[3, nt] nxt, double[3, ns] xs, double[ns] ws, int[1] if_self, inout double[nt3, ns3] T);
 */
static const char* stubids3_ = "Sto3dSLPnmat_mex(c i int[x], c i int[x], c i int[x], c i int[x], c i double[xx], c i double[xx], c i double[xx], c i double[x], c i int[x], c io double[xx])";

void mexStub3(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    int*        in0_ =0; /* nt         */
    int*        in1_ =0; /* ns         */
    int*        in2_ =0; /* nt3        */
    int*        in3_ =0; /* ns3        */
    double*     in4_ =0; /* xt         */
    double*     in5_ =0; /* nxt        */
    double*     in6_ =0; /* xs         */
    double*     in7_ =0; /* ws         */
    int*        in8_ =0; /* if_self    */
    double*     in9_ =0; /* T          */
    mwSize      dim10_;   /* 1          */
    mwSize      dim11_;   /* 1          */
    mwSize      dim12_;   /* 1          */
    mwSize      dim13_;   /* 1          */
    mwSize      dim14_;   /* 3          */
    mwSize      dim15_;   /* nt         */
    mwSize      dim16_;   /* 3          */
    mwSize      dim17_;   /* nt         */
    mwSize      dim18_;   /* 3          */
    mwSize      dim19_;   /* ns         */
    mwSize      dim20_;   /* ns         */
    mwSize      dim21_;   /* 1          */
    mwSize      dim22_;   /* nt3        */
    mwSize      dim23_;   /* ns3        */

    dim10_ = (mwSize) mxWrapGetScalar(prhs[10], &mw_err_txt_);
    dim11_ = (mwSize) mxWrapGetScalar(prhs[11], &mw_err_txt_);
    dim12_ = (mwSize) mxWrapGetScalar(prhs[12], &mw_err_txt_);
    dim13_ = (mwSize) mxWrapGetScalar(prhs[13], &mw_err_txt_);
    dim14_ = (mwSize) mxWrapGetScalar(prhs[14], &mw_err_txt_);
    dim15_ = (mwSize) mxWrapGetScalar(prhs[15], &mw_err_txt_);
    dim16_ = (mwSize) mxWrapGetScalar(prhs[16], &mw_err_txt_);
    dim17_ = (mwSize) mxWrapGetScalar(prhs[17], &mw_err_txt_);
    dim18_ = (mwSize) mxWrapGetScalar(prhs[18], &mw_err_txt_);
    dim19_ = (mwSize) mxWrapGetScalar(prhs[19], &mw_err_txt_);
    dim20_ = (mwSize) mxWrapGetScalar(prhs[20], &mw_err_txt_);
    dim21_ = (mwSize) mxWrapGetScalar(prhs[21], &mw_err_txt_);
    dim22_ = (mwSize) mxWrapGetScalar(prhs[22], &mw_err_txt_);
    dim23_ = (mwSize) mxWrapGetScalar(prhs[23], &mw_err_txt_);

    if (mxGetM(prhs[0])*mxGetN(prhs[0]) != dim10_) {
        mw_err_txt_ = "Bad argument size: nt";        goto mw_err_label;
    }

    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != dim11_) {
        mw_err_txt_ = "Bad argument size: ns";        goto mw_err_label;
    }

    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != dim12_) {
        mw_err_txt_ = "Bad argument size: nt3";        goto mw_err_label;
    }

    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != dim13_) {
        mw_err_txt_ = "Bad argument size: ns3";        goto mw_err_label;
    }

    if (mxGetM(prhs[4]) != dim14_ ||
        mxGetN(prhs[4]) != dim15_) {
        mw_err_txt_ = "Bad argument size: xt";
        goto mw_err_label;
    }

    if (mxGetM(prhs[5]) != dim16_ ||
        mxGetN(prhs[5]) != dim17_) {
        mw_err_txt_ = "Bad argument size: nxt";
        goto mw_err_label;
    }

    if (mxGetM(prhs[6]) != dim18_ ||
        mxGetN(prhs[6]) != dim19_) {
        mw_err_txt_ = "Bad argument size: xs";
        goto mw_err_label;
    }

    if (mxGetM(prhs[7])*mxGetN(prhs[7]) != dim20_) {
        mw_err_txt_ = "Bad argument size: ws";        goto mw_err_label;
    }

    if (mxGetM(prhs[8])*mxGetN(prhs[8]) != dim21_) {
        mw_err_txt_ = "Bad argument size: if_self";        goto mw_err_label;
    }

    if (mxGetM(prhs[9]) != dim22_ ||
        mxGetN(prhs[9]) != dim23_) {
        mw_err_txt_ = "Bad argument size: T";
        goto mw_err_label;
    }

    if (mxGetM(prhs[0])*mxGetN(prhs[0]) != 0) {
        in0_ = mxWrapGetArray_int(prhs[0], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in0_ = NULL;

    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != 0) {
        in1_ = mxWrapGetArray_int(prhs[1], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in1_ = NULL;

    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != 0) {
        in2_ = mxWrapGetArray_int(prhs[2], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in2_ = NULL;

    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != 0) {
        in3_ = mxWrapGetArray_int(prhs[3], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in3_ = NULL;

    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != 0) {
        if( mxGetClassID(prhs[4]) != mxDOUBLE_CLASS )
            mw_err_txt_ = "Invalid array argument, mxDOUBLE_CLASS expected";
        if (mw_err_txt_) goto mw_err_label;
#if MX_HAS_INTERLEAVED_COMPLEX
        in4_ = mxGetDoubles(prhs[4]);
#else
        in4_ = mxGetPr(prhs[4]);
#endif
    } else
        in4_ = NULL;

    if (mxGetM(prhs[5])*mxGetN(prhs[5]) != 0) {
        if( mxGetClassID(prhs[5]) != mxDOUBLE_CLASS )
            mw_err_txt_ = "Invalid array argument, mxDOUBLE_CLASS expected";
        if (mw_err_txt_) goto mw_err_label;
#if MX_HAS_INTERLEAVED_COMPLEX
        in5_ = mxGetDoubles(prhs[5]);
#else
        in5_ = mxGetPr(prhs[5]);
#endif
    } else
        in5_ = NULL;

    if (mxGetM(prhs[6])*mxGetN(prhs[6]) != 0) {
        if( mxGetClassID(prhs[6]) != mxDOUBLE_CLASS )
            mw_err_txt_ = "Invalid array argument, mxDOUBLE_CLASS expected";
        if (mw_err_txt_) goto mw_err_label;
#if MX_HAS_INTERLEAVED_COMPLEX
        in6_ = mxGetDoubles(prhs[6]);
#else
        in6_ = mxGetPr(prhs[6]);
#endif
    } else
        in6_ = NULL;

    if (mxGetM(prhs[7])*mxGetN(prhs[7]) != 0) {
        if( mxGetClassID(prhs[7]) != mxDOUBLE_CLASS )
            mw_err_txt_ = "Invalid array argument, mxDOUBLE_CLASS expected";
        if (mw_err_txt_) goto mw_err_label;
#if MX_HAS_INTERLEAVED_COMPLEX
        in7_ = mxGetDoubles(prhs[7]);
#else
        in7_ = mxGetPr(prhs[7]);
#endif
    } else
        in7_ = NULL;

    if (mxGetM(prhs[8])*mxGetN(prhs[8]) != 0) {
        in8_ = mxWrapGetArray_int(prhs[8], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in8_ = NULL;

    if (mxGetM(prhs[9])*mxGetN(prhs[9]) != 0) {
        in9_ = mxWrapGetArray_double(prhs[9], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in9_ = NULL;

    if (mexprofrecord_)
        mexprofrecord_[3]++;
    MWF77_Sto3dSLPnmat_mex(in0_, in1_, in2_, in3_, in4_, in5_, in6_, in7_, in8_, in9_);
    plhs[0] = mxCreateDoubleMatrix(dim22_, dim23_, mxREAL);
    mxWrapCopy_double(plhs[0], in9_, dim22_*dim23_);

mw_err_label:
    if (in0_)  mxFree(in0_);
    if (in1_)  mxFree(in1_);
    if (in2_)  mxFree(in2_);
    if (in3_)  mxFree(in3_);
    if (in8_)  mxFree(in8_);
    if (in9_)  mxFree(in9_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ---- matlab/stokes.mw: 11 ----
 * build_geometry_bvp_mex(int[1] p, int[1] np, char[slen] shape_name_c, int[1] slen, inout double[3, np] r, inout double[3, np] nx, inout double[3, np] xu, inout double[3, np] xv, inout double[np] w);
 */
static const char* stubids4_ = "build_geometry_bvp_mex(c i int[x], c i int[x], c i char[x], c i int[x], c io double[xx], c io double[xx], c io double[xx], c io double[xx], c io double[x])";

void mexStub4(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    int*        in0_ =0; /* p          */
    int*        in1_ =0; /* np         */
    char*       in2_ =0; /* shape_name_c */
    int*        in3_ =0; /* slen       */
    double*     in4_ =0; /* r          */
    double*     in5_ =0; /* nx         */
    double*     in6_ =0; /* xu         */
    double*     in7_ =0; /* xv         */
    double*     in8_ =0; /* w          */
    mwSize      dim9_;   /* 1          */
    mwSize      dim10_;   /* 1          */
    mwSize      dim11_;   /* slen       */
    mwSize      dim12_;   /* 1          */
    mwSize      dim13_;   /* 3          */
    mwSize      dim14_;   /* np         */
    mwSize      dim15_;   /* 3          */
    mwSize      dim16_;   /* np         */
    mwSize      dim17_;   /* 3          */
    mwSize      dim18_;   /* np         */
    mwSize      dim19_;   /* 3          */
    mwSize      dim20_;   /* np         */
    mwSize      dim21_;   /* np         */

    dim9_ = (mwSize) mxWrapGetScalar(prhs[9], &mw_err_txt_);
    dim10_ = (mwSize) mxWrapGetScalar(prhs[10], &mw_err_txt_);
    dim11_ = (mwSize) mxWrapGetScalar(prhs[11], &mw_err_txt_);
    dim12_ = (mwSize) mxWrapGetScalar(prhs[12], &mw_err_txt_);
    dim13_ = (mwSize) mxWrapGetScalar(prhs[13], &mw_err_txt_);
    dim14_ = (mwSize) mxWrapGetScalar(prhs[14], &mw_err_txt_);
    dim15_ = (mwSize) mxWrapGetScalar(prhs[15], &mw_err_txt_);
    dim16_ = (mwSize) mxWrapGetScalar(prhs[16], &mw_err_txt_);
    dim17_ = (mwSize) mxWrapGetScalar(prhs[17], &mw_err_txt_);
    dim18_ = (mwSize) mxWrapGetScalar(prhs[18], &mw_err_txt_);
    dim19_ = (mwSize) mxWrapGetScalar(prhs[19], &mw_err_txt_);
    dim20_ = (mwSize) mxWrapGetScalar(prhs[20], &mw_err_txt_);
    dim21_ = (mwSize) mxWrapGetScalar(prhs[21], &mw_err_txt_);

    if (mxGetM(prhs[0])*mxGetN(prhs[0]) != dim9_) {
        mw_err_txt_ = "Bad argument size: p";        goto mw_err_label;
    }

    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != dim10_) {
        mw_err_txt_ = "Bad argument size: np";        goto mw_err_label;
    }

    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != dim11_) {
        mw_err_txt_ = "Bad argument size: shape_name_c";        goto mw_err_label;
    }

    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != dim12_) {
        mw_err_txt_ = "Bad argument size: slen";        goto mw_err_label;
    }

    if (mxGetM(prhs[4]) != dim13_ ||
        mxGetN(prhs[4]) != dim14_) {
        mw_err_txt_ = "Bad argument size: r";
        goto mw_err_label;
    }

    if (mxGetM(prhs[5]) != dim15_ ||
        mxGetN(prhs[5]) != dim16_) {
        mw_err_txt_ = "Bad argument size: nx";
        goto mw_err_label;
    }

    if (mxGetM(prhs[6]) != dim17_ ||
        mxGetN(prhs[6]) != dim18_) {
        mw_err_txt_ = "Bad argument size: xu";
        goto mw_err_label;
    }

    if (mxGetM(prhs[7]) != dim19_ ||
        mxGetN(prhs[7]) != dim20_) {
        mw_err_txt_ = "Bad argument size: xv";
        goto mw_err_label;
    }

    if (mxGetM(prhs[8])*mxGetN(prhs[8]) != dim21_) {
        mw_err_txt_ = "Bad argument size: w";        goto mw_err_label;
    }

    if (mxGetM(prhs[0])*mxGetN(prhs[0]) != 0) {
        in0_ = mxWrapGetArray_int(prhs[0], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in0_ = NULL;

    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != 0) {
        in1_ = mxWrapGetArray_int(prhs[1], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in1_ = NULL;

    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != 0) {
        in2_ = mxWrapGetArray_char(prhs[2], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in2_ = NULL;

    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != 0) {
        in3_ = mxWrapGetArray_int(prhs[3], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in3_ = NULL;

    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != 0) {
        in4_ = mxWrapGetArray_double(prhs[4], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in4_ = NULL;

    if (mxGetM(prhs[5])*mxGetN(prhs[5]) != 0) {
        in5_ = mxWrapGetArray_double(prhs[5], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in5_ = NULL;

    if (mxGetM(prhs[6])*mxGetN(prhs[6]) != 0) {
        in6_ = mxWrapGetArray_double(prhs[6], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in6_ = NULL;

    if (mxGetM(prhs[7])*mxGetN(prhs[7]) != 0) {
        in7_ = mxWrapGetArray_double(prhs[7], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in7_ = NULL;

    if (mxGetM(prhs[8])*mxGetN(prhs[8]) != 0) {
        in8_ = mxWrapGetArray_double(prhs[8], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in8_ = NULL;

    if (mexprofrecord_)
        mexprofrecord_[4]++;
    MWF77_build_geometry_bvp_mex(in0_, in1_, in2_, in3_, in4_, in5_, in6_, in7_, in8_);
    plhs[0] = mxCreateDoubleMatrix(dim13_, dim14_, mxREAL);
    mxWrapCopy_double(plhs[0], in4_, dim13_*dim14_);
    plhs[1] = mxCreateDoubleMatrix(dim15_, dim16_, mxREAL);
    mxWrapCopy_double(plhs[1], in5_, dim15_*dim16_);
    plhs[2] = mxCreateDoubleMatrix(dim17_, dim18_, mxREAL);
    mxWrapCopy_double(plhs[2], in6_, dim17_*dim18_);
    plhs[3] = mxCreateDoubleMatrix(dim19_, dim20_, mxREAL);
    mxWrapCopy_double(plhs[3], in7_, dim19_*dim20_);
    plhs[4] = mxCreateDoubleMatrix(dim21_, 1, mxREAL);
    mxWrapCopy_double(plhs[4], in8_, dim21_);

mw_err_label:
    if (in0_)  mxFree(in0_);
    if (in1_)  mxFree(in1_);
    if (in2_)  mxFree(in2_);
    if (in3_)  mxFree(in3_);
    if (in4_)  mxFree(in4_);
    if (in5_)  mxFree(in5_);
    if (in6_)  mxFree(in6_);
    if (in7_)  mxFree(in7_);
    if (in8_)  mxFree(in8_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ---- matlab/stokes.mw: 14 ----
 * kerneldSMatrix_mex(int[1] p, int[1] n, int[1] n3, double[3, n] rxyz, double[3, n] nxyz, double[n] w, inout double[n3, n3] A);
 */
static const char* stubids5_ = "kerneldSMatrix_mex(c i int[x], c i int[x], c i int[x], c i double[xx], c i double[xx], c i double[x], c io double[xx])";

void mexStub5(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    int*        in0_ =0; /* p          */
    int*        in1_ =0; /* n          */
    int*        in2_ =0; /* n3         */
    double*     in3_ =0; /* rxyz       */
    double*     in4_ =0; /* nxyz       */
    double*     in5_ =0; /* w          */
    double*     in6_ =0; /* A          */
    mwSize      dim7_;   /* 1          */
    mwSize      dim8_;   /* 1          */
    mwSize      dim9_;   /* 1          */
    mwSize      dim10_;   /* 3          */
    mwSize      dim11_;   /* n          */
    mwSize      dim12_;   /* 3          */
    mwSize      dim13_;   /* n          */
    mwSize      dim14_;   /* n          */
    mwSize      dim15_;   /* n3         */
    mwSize      dim16_;   /* n3         */

    dim7_ = (mwSize) mxWrapGetScalar(prhs[7], &mw_err_txt_);
    dim8_ = (mwSize) mxWrapGetScalar(prhs[8], &mw_err_txt_);
    dim9_ = (mwSize) mxWrapGetScalar(prhs[9], &mw_err_txt_);
    dim10_ = (mwSize) mxWrapGetScalar(prhs[10], &mw_err_txt_);
    dim11_ = (mwSize) mxWrapGetScalar(prhs[11], &mw_err_txt_);
    dim12_ = (mwSize) mxWrapGetScalar(prhs[12], &mw_err_txt_);
    dim13_ = (mwSize) mxWrapGetScalar(prhs[13], &mw_err_txt_);
    dim14_ = (mwSize) mxWrapGetScalar(prhs[14], &mw_err_txt_);
    dim15_ = (mwSize) mxWrapGetScalar(prhs[15], &mw_err_txt_);
    dim16_ = (mwSize) mxWrapGetScalar(prhs[16], &mw_err_txt_);

    if (mxGetM(prhs[0])*mxGetN(prhs[0]) != dim7_) {
        mw_err_txt_ = "Bad argument size: p";        goto mw_err_label;
    }

    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != dim8_) {
        mw_err_txt_ = "Bad argument size: n";        goto mw_err_label;
    }

    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != dim9_) {
        mw_err_txt_ = "Bad argument size: n3";        goto mw_err_label;
    }

    if (mxGetM(prhs[3]) != dim10_ ||
        mxGetN(prhs[3]) != dim11_) {
        mw_err_txt_ = "Bad argument size: rxyz";
        goto mw_err_label;
    }

    if (mxGetM(prhs[4]) != dim12_ ||
        mxGetN(prhs[4]) != dim13_) {
        mw_err_txt_ = "Bad argument size: nxyz";
        goto mw_err_label;
    }

    if (mxGetM(prhs[5])*mxGetN(prhs[5]) != dim14_) {
        mw_err_txt_ = "Bad argument size: w";        goto mw_err_label;
    }

    if (mxGetM(prhs[6]) != dim15_ ||
        mxGetN(prhs[6]) != dim16_) {
        mw_err_txt_ = "Bad argument size: A";
        goto mw_err_label;
    }

    if (mxGetM(prhs[0])*mxGetN(prhs[0]) != 0) {
        in0_ = mxWrapGetArray_int(prhs[0], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in0_ = NULL;

    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != 0) {
        in1_ = mxWrapGetArray_int(prhs[1], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in1_ = NULL;

    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != 0) {
        in2_ = mxWrapGetArray_int(prhs[2], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in2_ = NULL;

    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != 0) {
        if( mxGetClassID(prhs[3]) != mxDOUBLE_CLASS )
            mw_err_txt_ = "Invalid array argument, mxDOUBLE_CLASS expected";
        if (mw_err_txt_) goto mw_err_label;
#if MX_HAS_INTERLEAVED_COMPLEX
        in3_ = mxGetDoubles(prhs[3]);
#else
        in3_ = mxGetPr(prhs[3]);
#endif
    } else
        in3_ = NULL;

    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != 0) {
        if( mxGetClassID(prhs[4]) != mxDOUBLE_CLASS )
            mw_err_txt_ = "Invalid array argument, mxDOUBLE_CLASS expected";
        if (mw_err_txt_) goto mw_err_label;
#if MX_HAS_INTERLEAVED_COMPLEX
        in4_ = mxGetDoubles(prhs[4]);
#else
        in4_ = mxGetPr(prhs[4]);
#endif
    } else
        in4_ = NULL;

    if (mxGetM(prhs[5])*mxGetN(prhs[5]) != 0) {
        if( mxGetClassID(prhs[5]) != mxDOUBLE_CLASS )
            mw_err_txt_ = "Invalid array argument, mxDOUBLE_CLASS expected";
        if (mw_err_txt_) goto mw_err_label;
#if MX_HAS_INTERLEAVED_COMPLEX
        in5_ = mxGetDoubles(prhs[5]);
#else
        in5_ = mxGetPr(prhs[5]);
#endif
    } else
        in5_ = NULL;

    if (mxGetM(prhs[6])*mxGetN(prhs[6]) != 0) {
        in6_ = mxWrapGetArray_double(prhs[6], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in6_ = NULL;

    if (mexprofrecord_)
        mexprofrecord_[5]++;
    MWF77_kerneldSMatrix_mex(in0_, in1_, in2_, in3_, in4_, in5_, in6_);
    plhs[0] = mxCreateDoubleMatrix(dim15_, dim16_, mxREAL);
    mxWrapCopy_double(plhs[0], in6_, dim15_*dim16_);

mw_err_label:
    if (in0_)  mxFree(in0_);
    if (in1_)  mxFree(in1_);
    if (in2_)  mxFree(in2_);
    if (in6_)  mxFree(in6_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ---- matlab/stokes.mw: 16 ----
 * sht_ana_rotgrid_mex(int[1] p, int[1] np, int[1] nc, double[np, nc] f, int[1] nshc, inout dcomplex[nshc, nc] shc);
 */
static const char* stubids6_ = "sht_ana_rotgrid_mex(c i int[x], c i int[x], c i int[x], c i double[xx], c i int[x], c io dcomplex[xx])";

void mexStub6(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    int*        in0_ =0; /* p          */
    int*        in1_ =0; /* np         */
    int*        in2_ =0; /* nc         */
    double*     in3_ =0; /* f          */
    int*        in4_ =0; /* nshc       */
    dcomplex*   in5_ =0; /* shc        */
    mwSize      dim6_;   /* 1          */
    mwSize      dim7_;   /* 1          */
    mwSize      dim8_;   /* 1          */
    mwSize      dim9_;   /* np         */
    mwSize      dim10_;   /* nc         */
    mwSize      dim11_;   /* 1          */
    mwSize      dim12_;   /* nshc       */
    mwSize      dim13_;   /* nc         */

    dim6_ = (mwSize) mxWrapGetScalar(prhs[6], &mw_err_txt_);
    dim7_ = (mwSize) mxWrapGetScalar(prhs[7], &mw_err_txt_);
    dim8_ = (mwSize) mxWrapGetScalar(prhs[8], &mw_err_txt_);
    dim9_ = (mwSize) mxWrapGetScalar(prhs[9], &mw_err_txt_);
    dim10_ = (mwSize) mxWrapGetScalar(prhs[10], &mw_err_txt_);
    dim11_ = (mwSize) mxWrapGetScalar(prhs[11], &mw_err_txt_);
    dim12_ = (mwSize) mxWrapGetScalar(prhs[12], &mw_err_txt_);
    dim13_ = (mwSize) mxWrapGetScalar(prhs[13], &mw_err_txt_);

    if (mxGetM(prhs[0])*mxGetN(prhs[0]) != dim6_) {
        mw_err_txt_ = "Bad argument size: p";        goto mw_err_label;
    }

    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != dim7_) {
        mw_err_txt_ = "Bad argument size: np";        goto mw_err_label;
    }

    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != dim8_) {
        mw_err_txt_ = "Bad argument size: nc";        goto mw_err_label;
    }

    if (mxGetM(prhs[3]) != dim9_ ||
        mxGetN(prhs[3]) != dim10_) {
        mw_err_txt_ = "Bad argument size: f";
        goto mw_err_label;
    }

    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != dim11_) {
        mw_err_txt_ = "Bad argument size: nshc";        goto mw_err_label;
    }

    if (mxGetM(prhs[5]) != dim12_ ||
        mxGetN(prhs[5]) != dim13_) {
        mw_err_txt_ = "Bad argument size: shc";
        goto mw_err_label;
    }

    if (mxGetM(prhs[0])*mxGetN(prhs[0]) != 0) {
        in0_ = mxWrapGetArray_int(prhs[0], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in0_ = NULL;

    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != 0) {
        in1_ = mxWrapGetArray_int(prhs[1], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in1_ = NULL;

    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != 0) {
        in2_ = mxWrapGetArray_int(prhs[2], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in2_ = NULL;

    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != 0) {
        if( mxGetClassID(prhs[3]) != mxDOUBLE_CLASS )
            mw_err_txt_ = "Invalid array argument, mxDOUBLE_CLASS expected";
        if (mw_err_txt_) goto mw_err_label;
#if MX_HAS_INTERLEAVED_COMPLEX
        in3_ = mxGetDoubles(prhs[3]);
#else
        in3_ = mxGetPr(prhs[3]);
#endif
    } else
        in3_ = NULL;

    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != 0) {
        in4_ = mxWrapGetArray_int(prhs[4], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in4_ = NULL;

    if (mxGetM(prhs[5])*mxGetN(prhs[5]) != 0) {
        if( mxGetClassID(prhs[5]) != mxDOUBLE_CLASS )
            mw_err_txt_ = "Invalid array argument, mxDOUBLE_CLASS expected";
        if (mw_err_txt_) goto mw_err_label;
        in5_ = mxWrapGetArray_dcomplex(prhs[5], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in5_ = NULL;

    if (mexprofrecord_)
        mexprofrecord_[6]++;
    MWF77_sht_ana_rotgrid_mex(in0_, in1_, in2_, in3_, in4_, in5_);
    plhs[0] = mxCreateDoubleMatrix(dim12_, dim13_, mxCOMPLEX);
    mxWrapCopy_dcomplex(plhs[0], in5_, dim12_*dim13_);

mw_err_label:
    if (in0_)  mxFree(in0_);
    if (in1_)  mxFree(in1_);
    if (in2_)  mxFree(in2_);
    if (in4_)  mxFree(in4_);
    if (in5_)  mxFree(in5_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ---- matlab/stokes.mw: 18 ----
 * ynm_all_mex(int[1] n, int[1] np, int[1] nm, double[np] u, double[np] v, inout dcomplex[np, nm] yn);
 */
static const char* stubids7_ = "ynm_all_mex(c i int[x], c i int[x], c i int[x], c i double[x], c i double[x], c io dcomplex[xx])";

void mexStub7(int nlhs, mxArray* plhs[],
              int nrhs, const mxArray* prhs[])
{
    const char* mw_err_txt_ = 0;
    int*        in0_ =0; /* n          */
    int*        in1_ =0; /* np         */
    int*        in2_ =0; /* nm         */
    double*     in3_ =0; /* u          */
    double*     in4_ =0; /* v          */
    dcomplex*   in5_ =0; /* yn         */
    mwSize      dim6_;   /* 1          */
    mwSize      dim7_;   /* 1          */
    mwSize      dim8_;   /* 1          */
    mwSize      dim9_;   /* np         */
    mwSize      dim10_;   /* np         */
    mwSize      dim11_;   /* np         */
    mwSize      dim12_;   /* nm         */

    dim6_ = (mwSize) mxWrapGetScalar(prhs[6], &mw_err_txt_);
    dim7_ = (mwSize) mxWrapGetScalar(prhs[7], &mw_err_txt_);
    dim8_ = (mwSize) mxWrapGetScalar(prhs[8], &mw_err_txt_);
    dim9_ = (mwSize) mxWrapGetScalar(prhs[9], &mw_err_txt_);
    dim10_ = (mwSize) mxWrapGetScalar(prhs[10], &mw_err_txt_);
    dim11_ = (mwSize) mxWrapGetScalar(prhs[11], &mw_err_txt_);
    dim12_ = (mwSize) mxWrapGetScalar(prhs[12], &mw_err_txt_);

    if (mxGetM(prhs[0])*mxGetN(prhs[0]) != dim6_) {
        mw_err_txt_ = "Bad argument size: n";        goto mw_err_label;
    }

    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != dim7_) {
        mw_err_txt_ = "Bad argument size: np";        goto mw_err_label;
    }

    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != dim8_) {
        mw_err_txt_ = "Bad argument size: nm";        goto mw_err_label;
    }

    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != dim9_) {
        mw_err_txt_ = "Bad argument size: u";        goto mw_err_label;
    }

    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != dim10_) {
        mw_err_txt_ = "Bad argument size: v";        goto mw_err_label;
    }

    if (mxGetM(prhs[5]) != dim11_ ||
        mxGetN(prhs[5]) != dim12_) {
        mw_err_txt_ = "Bad argument size: yn";
        goto mw_err_label;
    }

    if (mxGetM(prhs[0])*mxGetN(prhs[0]) != 0) {
        in0_ = mxWrapGetArray_int(prhs[0], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in0_ = NULL;

    if (mxGetM(prhs[1])*mxGetN(prhs[1]) != 0) {
        in1_ = mxWrapGetArray_int(prhs[1], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in1_ = NULL;

    if (mxGetM(prhs[2])*mxGetN(prhs[2]) != 0) {
        in2_ = mxWrapGetArray_int(prhs[2], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in2_ = NULL;

    if (mxGetM(prhs[3])*mxGetN(prhs[3]) != 0) {
        if( mxGetClassID(prhs[3]) != mxDOUBLE_CLASS )
            mw_err_txt_ = "Invalid array argument, mxDOUBLE_CLASS expected";
        if (mw_err_txt_) goto mw_err_label;
#if MX_HAS_INTERLEAVED_COMPLEX
        in3_ = mxGetDoubles(prhs[3]);
#else
        in3_ = mxGetPr(prhs[3]);
#endif
    } else
        in3_ = NULL;

    if (mxGetM(prhs[4])*mxGetN(prhs[4]) != 0) {
        if( mxGetClassID(prhs[4]) != mxDOUBLE_CLASS )
            mw_err_txt_ = "Invalid array argument, mxDOUBLE_CLASS expected";
        if (mw_err_txt_) goto mw_err_label;
#if MX_HAS_INTERLEAVED_COMPLEX
        in4_ = mxGetDoubles(prhs[4]);
#else
        in4_ = mxGetPr(prhs[4]);
#endif
    } else
        in4_ = NULL;

    if (mxGetM(prhs[5])*mxGetN(prhs[5]) != 0) {
        if( mxGetClassID(prhs[5]) != mxDOUBLE_CLASS )
            mw_err_txt_ = "Invalid array argument, mxDOUBLE_CLASS expected";
        if (mw_err_txt_) goto mw_err_label;
        in5_ = mxWrapGetArray_dcomplex(prhs[5], &mw_err_txt_);
        if (mw_err_txt_)
            goto mw_err_label;
    } else
        in5_ = NULL;

    if (mexprofrecord_)
        mexprofrecord_[7]++;
    MWF77_ynm_all_mex(in0_, in1_, in2_, in3_, in4_, in5_);
    plhs[0] = mxCreateDoubleMatrix(dim11_, dim12_, mxCOMPLEX);
    mxWrapCopy_dcomplex(plhs[0], in5_, dim11_*dim12_);

mw_err_label:
    if (in0_)  mxFree(in0_);
    if (in1_)  mxFree(in1_);
    if (in2_)  mxFree(in2_);
    if (in5_)  mxFree(in5_);
    if (mw_err_txt_)
        mexErrMsgTxt(mw_err_txt_);
}

/* ----
 */
void mexFunction(int nlhs, mxArray* plhs[],
                 int nrhs, const mxArray* prhs[])
{
    char id[4090];
    if (nrhs == 0) {
        mexPrintf("Mex function installed\n");
        return;
    }



    if (mxGetString(prhs[0], id, sizeof(id)) != 0)
        mexErrMsgTxt("Identifier should be a string");
    else if (strcmp(id, stubids1_) == 0)
        mexStub1(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, stubids2_) == 0)
        mexStub2(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, stubids3_) == 0)
        mexStub3(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, stubids4_) == 0)
        mexStub4(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, stubids5_) == 0)
        mexStub5(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, stubids6_) == 0)
        mexStub6(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, stubids7_) == 0)
        mexStub7(nlhs,plhs, nrhs-1,prhs+1);
    else if (strcmp(id, "*profile on*") == 0) {
        if (!mexprofrecord_) {
            mexprofrecord_ = (int*) malloc(8 * sizeof(int));
            mexLock();
        }
        memset(mexprofrecord_, 0, 8 * sizeof(int));
    } else if (strcmp(id, "*profile off*") == 0) {
        if (mexprofrecord_) {
            free(mexprofrecord_);
            mexUnlock();
        }
        mexprofrecord_ = NULL;
    } else if (strcmp(id, "*profile report*") == 0) {
        if (!mexprofrecord_)
            mexPrintf("Profiler inactive\n");
        mexPrintf("%d calls to matlab/stokes.mw:2\n", mexprofrecord_[1]);
        mexPrintf("%d calls to matlab/stokes.mw:4\n", mexprofrecord_[2]);
        mexPrintf("%d calls to matlab/stokes.mw:6\n", mexprofrecord_[3]);
        mexPrintf("%d calls to matlab/stokes.mw:11\n", mexprofrecord_[4]);
        mexPrintf("%d calls to matlab/stokes.mw:14\n", mexprofrecord_[5]);
        mexPrintf("%d calls to matlab/stokes.mw:16\n", mexprofrecord_[6]);
        mexPrintf("%d calls to matlab/stokes.mw:18\n", mexprofrecord_[7]);
    } else if (strcmp(id, "*profile log*") == 0) {
        FILE* logfp;
        if (nrhs != 2 || mxGetString(prhs[1], id, sizeof(id)) != 0)
            mexErrMsgTxt("Must have two string arguments");
        logfp = fopen(id, "w+");
        if (!logfp)
            mexErrMsgTxt("Cannot open log for output");
        if (!mexprofrecord_)
            fprintf(logfp, "Profiler inactive\n");
        fprintf(logfp, "%d calls to matlab/stokes.mw:2\n", mexprofrecord_[1]);
        fprintf(logfp, "%d calls to matlab/stokes.mw:4\n", mexprofrecord_[2]);
        fprintf(logfp, "%d calls to matlab/stokes.mw:6\n", mexprofrecord_[3]);
        fprintf(logfp, "%d calls to matlab/stokes.mw:11\n", mexprofrecord_[4]);
        fprintf(logfp, "%d calls to matlab/stokes.mw:14\n", mexprofrecord_[5]);
        fprintf(logfp, "%d calls to matlab/stokes.mw:16\n", mexprofrecord_[6]);
        fprintf(logfp, "%d calls to matlab/stokes.mw:18\n", mexprofrecord_[7]);
        fclose(logfp);
    } else
        mexErrMsgTxt("Unknown identifier");
}

